kkrt-labs/kakarot

src/kakarot/stack.cairo
tests/units/kakarot/test_stack.cairo

:white_check_mark: Adding stack tests

---

src/kakarot/instructions/arithmetic_operations.cairo
tests/units/kakarot/instructions/test_arithmetic_operations.cairo
tests/units/kakarot/test_execution_context.cairo
tests/units/kakarot/test_memory.cairo

Adding tests
I started a refactoring in the arithmetic_operations file. I think it could be better. But that's a first step.

:white_check_mark: Adding tests

---

src/kakarot/instructions/exchange_operations.cairo

Remove unused imports in exchange operations

Remove unused imports

---

README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
tests/cases/006.json
tests/units/kakarot/test_basic.cairo

Issue Number: fixes #56
0x38 - CODESIZE opcode is supported

✨ 0x38 - CODESIZE

---

README.md
docs/supported_opcodes.md
src/kakarot/constants.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
tests/cases/007.json
tests/units/kakarot/test_basic.cairo

Issue Number: fixes #59
0x46 - CHAINID opcode is supported

✨ 0x46 - CHAINID

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/constants.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
tests/cases/008.json
tests/units/kakarot/test_basic.cairo

Issue Number: fixes #64 
0x41 - COINBASE opcode is supported

✨ 0x41 - COINBASE

---

README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/SECURITY.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/003_iszero.json
tests/units/kakarot/test_basic.cairo

- Implement ISZERO opcode
- Update doc
- Highlight the priority for the MVP in Contributing section

:sparkles: ISZERO comparison opcode

---

docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/003_eq.json
tests/units/kakarot/test_basic.cairo

implements issue #39
Issue Number: #39 
```
Stack input
a: left side integer.
b: right side integer.
Stack output
a == b: 1 if the left side is equal to the right side, 0 otherwise.
Examples
Input	Output			Input	Output
1	10	1		1	10	0
2	10			2	5	
Reproduce in playground.
Error cases
The state changes done by the current context are reverted in those cases:
Not enough gas.
Not enough values on the stack.
```

feat: implement 0x14 - EQ opcode

---

src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/stack.cairo
tests/units/kakarot/test_stack.cairo

Reverts sayajin-labs/kakarot#60

Revert ":sparkles: Implement stack pop_n"

---

.markdownlint.json
.prettierrc.json
LICENSE
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/SECURITY.md
docs/mvp/README.md

Lines too long in markdown files
No issue, just for fun
- added a markdownlint file and lint files
- fix some typos

Cosmetic only: fix some typos and markdown linting

---

README.md
docs/supported_opcodes.md
src/kakarot/constants.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
tests/cases/010.json
tests/units/kakarot/test_basic.cairo

0x43 number

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/011.json
tests/units/kakarot/instructions/test_arithmetic_operations.cairo
tests/units/kakarot/test_basic.cairo
tests/units/kakarot/test_execution_context.cairo

:sparkles: Introduce 0x42 - Timestamp

---

src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/comparison_operations.cairo
src/kakarot/instructions/duplication_operations.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/exchange_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/push_operations.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/kakarot/stack.cairo
tests/units/kakarot/instructions/test_arithmetic_operations.cairo
tests/units/kakarot/instructions/test_block_information.cairo
tests/units/kakarot/library.cairo
tests/units/kakarot/test_basic.cairo
tests/units/kakarot/test_execution_context.cairo
tests/units/kakarot/test_memory.cairo
tests/units/kakarot/test_stack.cairo
tests/utils.cairo

Can't use the bitwise builtin
Can use the bitwise builtin

feat(bitwise): add bitwise everywhere

---

docs/mvp/resources/support.md

:memo: Update MVP supported opcodes

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/003_and.json
tests/cases/003_or.json
tests/units/kakarot/test_basic.cairo

:sparkles: Introduce AND + OR opcodes

---

README.md

:memo: Update opcodes chart

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/003_not.json
tests/test_basic.py

:sparkles: Introduce 0x19 - Bitwise NOT operation

---

Makefile

Build is not working
Switch build to compile and fix compilation

feat(makefile): fix compile rule

---

README.md

Update Readme: remove protostar gif and add some Mac M1 learnings on Cairo
-
-
-

Remove protostar gif and add Mac M1 install helper

---

README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/memory_operations.cairo
tests/cairo_files/instructions/test_memory_operations.cairo
tests/units/instructions/test_memory_operations.py

Adding POP opcode in Kakarot
- Add POP opcode
- Still missing: update "supported opcode" list
- Succesfully running tests with new setup

feat: add POP opcode

---

docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cases/003/sar/1.json
tests/cases/003/sar/10.json
tests/cases/003/sar/11.json
tests/cases/003/sar/12.json
tests/cases/003/sar/13.json
tests/cases/003/sar/14.json
tests/cases/003/sar/15.json
tests/cases/003/sar/16.json
tests/cases/003/sar/2.json
tests/cases/003/sar/3.json
tests/cases/003/sar/4.json
tests/cases/003/sar/5.json
tests/cases/003/sar/6.json
tests/cases/003/sar/7.json
tests/cases/003/sar/8.json
tests/cases/003/sar/9.json
tests/test_basic.py

No support for SAR
Closes #53 
- Add support for 0x1d (SAR)
- Add tests for SAR
Implementation might not be the faster due to `if` branch. We can try to optimize it later on if need be.

feat: add SAR (0x1d)

---

README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
tests/cases/021.json
tests/test_basic.py

- 0x44 Difficulty - returning 0 - opcode
-
-

0x44 Difficulty

---

README.md
docs/supported_opcodes.md
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
tests/cases/019.json
tests/test_basic.py

- Jumpdest opcode implemented 
-
-

0x5b JUMPDEST

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/memory_operations.cairo
tests/cairo_files/test_execution_context.cairo
tests/cases/020.json
tests/test_basic.py
tests/units/test_execution_context.py

Issue Number: #81 
- JUMP Opcode
- Added function to update the program counter to a provided value
- Small adjustments to JUMPDEST
- Tests covering new functionality

Feat/0x56 JUMP opcode

---

README.md
docs/mvp/resources/support.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/memory_operations.cairo
tests/cases/022.json
tests/test_basic.py

Issue Number: #80 
- 0x57 JUMPI opcode
-
-

feat/0x57 JUMPI opcode

---

README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/block_information.cairo
tests/cases/023.json
tests/test_basic.py

Issue Number: 86
- Implemented opcode 0x48 BASEFEE

0x48 BASEFEE opcode

---

.github/workflows/test.yml
Makefile
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/model.cairo

feat(make): format + format-check

---

src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/kakarot.cairo

Stack isn't properly updated when storing word in memory and when hashing a word
Stack is properly updated with the latest version of it

feat(memory + sha3): fix wrong stack update

---

src/kakarot/memory.cairo
src/kakarot/model.cairo

- Add init_offset and change logic
-
-

Init_offset implementation

---

src/kakarot/instructions/sha3.cairo
src/kakarot/kakarot.cairo
src/kakarot/memory.cairo
src/kakarot/model.cairo
src/utils/utils.cairo
tests/cases/013/sha3prime.json
tests/cases/memory/002.json
tests/test_basic.py
tests/utils.cairo

feat(mstore): refacto

---

.github/workflows/test.yml
Makefile
coverage/coverage.py
src/kakarot/execution_context.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
tests/cairo_files/instructions/test_block_information.cairo
tests/test_basic.py
tests/units/instructions/test_arithmetic_operations.py
tests/units/instructions/test_block_information.py
tests/units/instructions/test_memory_operations.py
tests/units/test_execution_context.py
tests/units/test_memory.py
tests/units/test_stack.py

We don't mesure coverage
Now we do

feat(coverage): add coverage for the project

---

src/kakarot/memory.cairo
tests/cases/memory/009.json
tests/cases/memory/010.json
tests/cases/memory/011.json
tests/cases/memory/012.json
tests/test_basic.py

- Added tests and fixed little typo
-
-

Added MSTORE Tests and fixed small typo

---

src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/comparison_operations.cairo
tests/cairo_files/instructions/test_comparison_operations.cairo
tests/cairo_files/test_execution_context.cairo
tests/units/instructions/test_arithmetic_operations.py
tests/units/instructions/test_comparison_operations.py

:sparkles: Using Stack.pop_n

---

.github/workflows/test.yml
Makefile

feat(Makefile): use poetry in makefile

---

docs/mvp/README.md
docs/mvp/resources/counter.md
docs/mvp/resources/erc20.md

feat: add "Counter" smart contract support README file for MVP

---

Makefile
README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/comparison_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/memory.cairo
tests/conftest.py
tests/test_zk_evm.py

0x53 MSTORE8(Rebased)

---

.github/workflows/test.yml
tests/conftest.py
tests/test_zk_evm.py

feat(ci): enable format check

---

src/kakarot/instructions/logging_operations.cairo

🚧 init logging operations

---

README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/memory.cairo
src/utils/utils.cairo
tests/conftest.py
tests/test_zk_evm.py

- 0x37 Calldatacopy opcode
- Changed "store_n" function to receive a felt* instead of Uint256 for cases where byte_sizes > 32
-

0x37 CALLDATACOPY

---

src/kakarot/memory.cairo

refacto(memory): remove ugly tempvars

---

.gitignore
src/kakarot/accounts/contract/contract_account.cairo
src/kakarot/accounts/contract/library.cairo
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/kakarot/model.cairo
tests/integrations/mock_kakarot.cairo
tests/integrations/mock_kakarot_abi.json
tests/test_zk_evm.py

Ethlisbon hackathon

---

Makefile
README.md
docs/supported_opcodes.md
src/kakarot/instructions.cairo
src/kakarot/instructions/logging_operations.cairo
tests/test_zk_evm.py

Issue Number: #178 
Fixes #178 
-
-
-

feat(opcode): add log0, log1, log2, log3, log4 + tests + doc

---

.gitignore
Makefile
src/kakarot/kakarot.cairo
src/kakarot/library.cairo

New accounts addresses printed in kakarot deploy
-
-
-

feat: add starknet contract address in deploy account

---

tests/test_zk_evm.py

feat(tests): fix tests that abdel broke

---

src/kakarot/accounts/contract/library.cairo
src/kakarot/accounts/registry/account_registry.cairo
src/kakarot/accounts/registry/library.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
tests/conftest.py
tests/test_zk_evm.py
tests/units/test_account_registry.py
tests/units/test_contract_account.py

deploy & account_contract not working
`zk_evm.deploy` works

Misc bug fixes and tests

---

tests/test_zk_evm.py

Function is not tested
Just run the two first test of `execute` with `execute_at_code`.

Add test for execute_at_address

---

.gitignore
Makefile
poetry.lock
pyproject.toml
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/duplication_operations.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/exchange_operations.cairo
src/kakarot/instructions/logging_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/push_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/kakarot/stack.cairo
tests/cairo_files/test_memory.cairo
tests/cairo_files/test_stack.cairo

- Clean unused implicit args
- refacto swap
- remove unused imports
- cairo lint rule

Clean code

---

src/kakarot/accounts/contract/contract_account.cairo
src/kakarot/accounts/contract/library.cairo
src/kakarot/accounts/eoa/library.cairo
src/kakarot/accounts/registry/account_registry.cairo
src/kakarot/accounts/registry/library.cairo
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/duplication_operations.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/exchange_operations.cairo
src/kakarot/instructions/logging_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/push_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/utils/utils.cairo

docs: first round of comment correction and extensions

---

poetry.lock
pyproject.toml
tests/conftest.py

update(coverage): bump coverage version

---

.github/ISSUE_TEMPLATE/04_NEW_OPCODE.yml

Add Byzantium in "since" field
-
-
-

Update Opcode Issue Template

---

README.md
docs/supported_opcodes.md

Add issue link for every remaining opcode.
See rich diff : https://github.com/sayajin-labs/kakarot/pull/262/files?short_path=d3c5251#diff-d3c5251c744945bd3b7adbd0dfce4841ae65457880d9d63833b0fddd39db4d8b

doc(opcodes) add link to related issues for missing opcodes

---

src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo

misinformation in comments

---

tests/integrations/test_cases/execute.py

Re-activate tests now that related feature has been fixed

test: re-enable tests for fixed features

---

scripts/check_resources.py

A previous merge updated the CI to display all the available artifacts' results. However, it stopped checking the current branch against main.
The local tests (ie. the one from the CI run) are compared against the latest "main" results again.
I've also updated the merge ops to use only the tests in common in between different branches to compares metrics.

Fix CI not checking local results

---

src/kakarot/instructions.cairo
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/utils/utils.cairo

Issue Number: Fix #307 
- Use `!=` instead of `==` for boolean comparisons
- Use `TRUE` or `FALSE` instead of `0` or `1` for readability

perf: change boolean comparisons to `!=`

---

tests/cairo_files/instructions/test_arithmetic_operations.cairo
tests/cairo_files/instructions/test_block_information.cairo
tests/cairo_files/instructions/test_comparison_operations.cairo
tests/cairo_files/instructions/test_memory_operations.cairo
tests/cairo_files/instructions/test_push_operations.cairo
tests/cairo_files/instructions/test_system_operations.cairo
tests/units/instructions/test_push_operations.py
tests/utils/utils.cairo

Remove duplicated code in tests by factorizing context initialization

refactor: remove unused helpers and rename utils

---

tests/solidity_files/ERC20.sol

The ERC20.sol file taken from Solmate's repo was truncated to fit in kakarot (removed the EIP Permit implementation).
The original file including the EIP Permit implementation is used in tests.
We could add the ERC1155.sol in another PR, as discussed in the community call.

Use plain Solmate's implemetation (re-put EIP Permit)

---

.github/workflows/test.yml
src/kakarot/library.cairo

Issue Number: Fix #296 
- change formatting check in CI from blocking ❌ a PR
- Format all cairo files and commit diff to the pr branch

dev: change formatting check in ci

---

src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/memory.cairo
src/utils/utils.cairo

Refactoring some code to cut some if-else branches and removing some unused vars
This shouldn't affect the behavior.

refactor: cutting some branches + renaming unused args to _

---

.github/workflows/test.yml
src/kakarot/instructions/arithmetic_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/memory.cairo
src/utils/utils.cairo
tests/cairo_files/instructions/test_exchange_operations.cairo
tests/units/instructions/test_exchange_operations.py

No test coverage for `exchange operations` instruction logic.
Issue Number: #316 
Adds tests for `exchange_operations` instruction logic
-
-
-

tests: Add tests for opcodes SWAPX 

---

tests/cairo_files/instructions/test_push_operations.cairo
tests/units/instructions/test_push_operations.py
tests/utils/utils.cairo

test: add tests for push 17-32

---

tests/cairo_files/instructions/test_stop_and_arithmetic_operations.cairo
tests/cairo_files/test_instructions.cairo
tests/units/instructions/test_stop_and_arithmetic_operations.py
tests/units/test_instructions.py

test: add test_instructions

---

tests/cairo_files/instructions/test_duplication_operations.cairo
tests/units/instructions/test_duplication_operations.py
tests/utils/utils.cairo

Issue Number: Fix #330 
- add unit tests for DUP opcodes (DUP1 to DUP16, `exec_dup_i`)
- add helper test functions
- push_elements_in_range_to_stack
- assert_stack_len_16bytes_equal

test: add test coverage for DUP

---

README.md

Adding FAQ about Kakarot to the readme
Adding common questions about Kakarot
After talking with Elias we agreed to add FAQ about Kakarot on the Github

Add FAQ about Kakarot project to README.md

---

src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
tests/cairo_files/instructions/test_environmental_information.cairo
tests/integrations/test_kakarot.py
tests/units/instructions/test_environmental_information.py

A lack of implementation of EXTCODECOPY opcode.
Issue Number: #95 
An implementation of EXTCODECOPY opcode.
-
-
-

feat EXTCODECOPY

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template uses "Issue Number"  keyword
The PR template uses "Resolves", which is part of the dedicated github keyword to automatically close the issue upon merge, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
The complete list of possible kw are: 
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

Use Resolves to automatically close the corresponding issue upon merge

---

src/kakarot/accounts/contract/contract_account.cairo
src/kakarot/accounts/contract/library.cairo
src/kakarot/accounts/registry/account_registry.cairo
src/kakarot/accounts/registry/library.cairo
src/kakarot/constants.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/library.cairo
src/utils/utils.cairo
tests/fixtures/3_account_registry.py
tests/unit/src/kakarot/instructions/test_system_operations.cairo
tests/unit/src/kakarot/instructions/test_system_operations.py

Resolves: #253 #259 
I am wondering if we should push further the factorization of the `kakarot.deploy` and `exec_create` methods.

feat: CREATE and CREATE2 opcodes

---

tests/unit/src/kakarot/instructions/test_comparison_operations.cairo
tests/unit/src/kakarot/instructions/test_comparison_operations.py

Resolves #329
- tests for XOR opcode
- tests for BYTE opcode
- bitwise test for AND opcode
- bitwise test for OR opcode

Test coverage for xor and byte

---

.gitignore
README.md
docs/CONTRIBUTING.md

docs: update documentation

---

README.md
docs/mvp/README.md
docs/mvp/resources/erc20.md
docs/supported_opcodes.md

docs: update supported opcodes

---

src/kakarot/model.cairo

no doc in model
Resolves #<379>
doc in model.cairo
-
-
-
Time spent on this PR:  0.2 days

Documentation model.cairo

---

src/kakarot/instructions/environmental_information.cairo
tests/unit/src/kakarot/instructions/test_environmental_information.cairo

`extcodesize` implementation did not mention the warm/code accounts and how it influences its dynamic gas costs
Resolves #340 
`extcodesize` implementation now mentions the warm/code accounts and how it influences its dynamic gas costs, and increments gas accordingly.
-
-
-
Time spent on this PR:  .25 days

feat: integrate warm/cold account concepts in EXTCODEXXX opcodes (#340)

---

src/kakarot/instructions/block_information.cairo
tests/integration/bytecode/test_cases.py

Resolves #308 
-
-
-
Time spent on this PR:  0.1day

fix: fix basefee test

---

src/kakarot/kakarot.cairo

fix: fix doc comments of execute and execute_at_address

---

src/kakarot/constants.cairo
src/kakarot/precompiles/ecadd.cairo
src/kakarot/precompiles/precompiles.cairo
src/utils/utils.cairo
tests/unit/src/kakarot/precompiles/test_ecadd.cairo
tests/unit/src/kakarot/precompiles/test_ecadd.py

There is no ecAdd implementation.
Resolves #362 
- Implements ecAdd precompile and a unit test.

feat: add ecAdd precompile

---

README.md

Diagram in README is not up to date
Diagram shows 100% opcodes.

Remove unsupported opcode section

---

pyproject.toml
src/kakarot/instructions.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/precompiles/ec_recover.cairo
src/kakarot/precompiles/ecadd.cairo
src/kakarot/precompiles/precompiles.cairo
tests/integration/bytecode/test_cases.py
tests/unit/src/kakarot/precompiles/test_ec_recover.cairo
tests/unit/src/kakarot/precompiles/test_ec_recover.py

Not implemented
Resolves #357 
Implemented
Fix some bugs related to Precompiles when used in integration test. We need to add integration test for all opcodes!

[Precompiles] ecrecover

---

src/kakarot/instructions/stop_and_arithmetic_operations.cairo
tests/integration/solidity_contracts/Counter/Counter.sol
tests/integration/solidity_contracts/Counter/test_counter.py

Minimal working example of error cases that came up when testing the solmates erc721 impl. The decrementing comes up in `burn` and `transferFrom` and tests involving these had failure. See: https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC721.sol#L178
-
-
-
Time spent on this PR:  1/4 of a day

add unchecked and in place cases for decrementing

---

tests/integration/conftest.py
tests/integration/solidity_contracts/Solmate/test_erc20.py

Incomplete integration test coverage for the solmates erc20 contract.
Resolves #352 
Richer integration testing ported from solmates [here](https://github.com/transmissions11/solmate/blob/main/src/test/ERC20.t.sol)
-
-
-
Time spent on this PR:  3/4s of a day

Complete solmate Erc20 integration testing (#352)

---

README.md
docs/general/kakarot_components.md

Fix: typos

---

Makefile
poetry.lock
pyproject.toml
tests/fixtures/1_starknet.py
tests/fixtures/6_kethaa.py
tests/integration/conftest.py
tests/integration/solidity_contracts/Solmate/test_erc20.py
tests/integration/solidity_contracts/Solmate/test_erc721.py
tests/unit/src/kakarot/precompiles/test_datacopy.py
tests/unit/src/kakarot/precompiles/test_ec_recover.py
tests/unit/src/kakarot/precompiles/test_precompiles.py
tests/unit/src/utils/test_utils.py
tests/utils/signer.py

Some files have unused imports and variables
Added the tool `autoflake` to format-check and format to check and automatically fix these issues.
Time spent on this PR:  0.5

Add autoflake to format and poetry check to build

---

.gitignore
poetry.lock
pyproject.toml
src/kakarot/precompiles/precompiles.cairo
src/kakarot/precompiles/sha256.cairo
src/utils/sha_256/packed_sha256.cairo
src/utils/utils.cairo
tests/integration/bytecode/test_cases.py
tests/unit/src/kakarot/precompiles/test_sha256.cairo
tests/unit/src/kakarot/precompiles/test_sha256.py
tests/unit/src/utils/test_utils.cairo
tests/unit/src/utils/test_utils.py

Time spent on this PR: 1.5 day
Resolves #358 
- add SHA2-256 precompile implementation
- add utils for SHA256 precompile and tests
- add unit and integration tests for SHA256

feat: add SHA2-256 precompile

---

pyproject.toml
src/kakarot/execution_context.cairo
src/kakarot/instructions.cairo
src/kakarot/instructions/environmental_information.cairo
tests/integration/conftest.py
tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py

Token addresses are random instead the same one as in the original test.
Test using `createPair` is skipped
Resolves #467 #452 
All tests pass as in the original file

UniswapV2Factory full test

---

ci/Dockerfile
ci/README.md
ci/setup_16.x

Add a dockerfile to generate image used by self hosted github runner.
A dockerfile to generate image used by self hosted github runner is present in `ci` directory..
Resolves #480 
-
-
-

CI: #480: add dockerfile to generate image used by self hosted github runner

---

src/kakarot/accounts/contract/contract_account.cairo

fix: update get_evm_address to view

---

docs/CONTRIBUTING.md

Time spent on this PR: 10 minutes
-
-
-

docs: add caveat for python3.9-dev

---

src/kakarot/accounts/eoa/library.cairo

While working on the other task I noticed this library has some imports which are not used. I've run `test_eoa.py` and it's passing.
-
-
-

refactor: eoa library file, remove unnecessary imports, use constants

---

src/kakarot/accounts/contract/contract_account.cairo
src/kakarot/accounts/contract/library.cairo

Time spent on this PR: 0,5 days 
In the fuction by codelane there is unecessary code.
Resolves  #513
Suppression of alloc locals from the body 
-
-
-

Remove unneeded code 

---

.github/workflows/deployments.yml

Workflow is not running
workflow is running

Fix python version in deployment workflow

---

src/kakarot/instructions/system_operations.cairo
tests/unit/src/kakarot/instructions/test_system_operations.cairo
tests/unit/src/kakarot/instructions/test_system_operations.py

Adds transfer of value when executing `CALLCODE`.
Time spent on this PR: 0.2 days
Executing `CALLCODE` does not transfer any value to the target `account`.
Resolves #543 
- `CALLCODE` transfers `value` to `account`.
- Additional unit testing for `CALLCODE` opcode value transfer.

feat: transfer value callcode

---

.github/workflows/ci.yml
.github/workflows/deployments.yml
scripts/utils.py
src/kakarot/library.cairo
tests/utils/helpers.py

After removing the hardcoded Account for devnet, `get_account` was broken as testnet account uses `getPublicKey` case
Fix `scripts.utils.get_account` for devnet

Try getPublicKey if get_public_key does not exist

---

.github/workflows/ci.yml
.github/workflows/deployments.yml

Switch from self hosted runners to managed runners

feat: remove self-hosted runners

---

scripts/constants.py
scripts/deploy_kakarot.py

An error caused the deployment script to crash when missing an evm private key in the .env file.
Time spent on this PR: N/A
Error in script prevents CI deployment of contracts.
Resolves N/A
- Scripts are updated in order to allow deployment with missing evm private key.

fix: update scripts

---

src/kakarot/accounts/eoa/library.cairo

function src/kakarot/accounts/eoa/library.cairo 
Time spent on this PR: apporx 1.5 hour
Current behavior doesn't changed improved development environment quality by adding comments
Resolves #516 
- Added comments

Related comments for the EOA library functions added

---

scripts/artifacts.py
scripts/constants.py
scripts/utils/kakarot.py
tests/src/kakarot/precompiles/test_sha256.py

Update constants layout by moving KAKAROT_ADDRESS to the kakarot utils in order to avoid pulling deployments.
Time spent on this PR: N/A
Deployments get pulled when ever constants.py is used, causing the deploy_kakarot script to fail.
Resolves N/A
- Deployments are only pulled when necessary (currently only in utils/kakarot.py).

fix: update constants

---

.env_example
README.md

There are inconsistencies in the **README** and the **.env.example** file as described in #571.
Resolves #571 .
It resolves all issues of #571 .
The updated keypair in the documentation is a valid keypair automatically generated from starknet-devnet.

fix(#571): fix errors in readme and .env.example, issue #571

---

scripts/utils/kakarot.py

The Kakarot contract has been refactored with `eth_send_transaction` and `eth_call` function. This PR updates the kakarot script in order to match this change.
Time spent on this PR: NA
The kakarot script fails to deploy, execute or call the Kakarot contract given the API change.
Resolves NA
The kakarot script fixed.
- Refactoring of the kakarot script to match Kakarot API change.

fix: update kakarot interaction script

---

scripts/utils/kakarot.py
src/kakarot/accounts/library.cairo
src/kakarot/kakarot.cairo

Remove events fetching error temporary fix

---

.env.example
scripts/compile_kakarot.py
scripts/constants.py
scripts/deploy_kakarot.py
scripts/utils/kakarot.py
scripts/utils/starknet.py

Time spent on this PR: 0.5 days
In the scripts/constants.py file, there are a bunch of parameters that need to be updated whenever we need to add a new chain.
The const definition has been updated to instead be a list of chain, each with all their parameters.

Refacto chain definition

---

scripts/deploy_kakarot.py
scripts/utils/starknet.py

Some code is run only when STARKNET_NETWORK=madara. We need to run it when network is
sharingan as well
Works on sharingan
First Kakarot deployment ✅ on sharingan!
Address: 0x3fc7138043e914a2061c128fd4a868a15361f1ef8bdeaade0e282995389dcf
Just deployed also an ERC20, address is 0x9bC9f3e18Ca7B721aE08D0c43Cc67D05ffc73f11

Add madara hacks to sharingan

---

scripts/utils/starknet.py
src/kakarot/execution_context.cairo
tests/fixtures/starknet.py
tests/utils/reporting.py

Time spent on this PR: 1 day
No way to easily extract all the hints used.
Added a (chat GPT generated) script

Minors updates founds along the way of debuging kakarot in madara/katana

---

docker/katana/Dockerfile
docker/katana/scripts/download_katana.sh

Fix Katana's image, in #605 , during rebase, wrong changes were accepted, which ended up mixing old and new images. This PR fixes it.
Resolves #612 
- The docker image should build properly on the CI

fix: fix katana docker image

---

Makefile
scripts/constants.py
scripts/utils/kakarot.py
scripts/utils/starknet.py

The "devnet" name is used for the "starknet-devnet", but several networks are "devnets" (madara, katana, starknet-devnet)
for instance. For all these networks, it's interesting to have, for example, the debug_info.
Added the `devnet: bool` field of the NETWORK config.
Added also `check_interval` and `max_wait` which were somehow hardcoded in `wait_for_tx` (might be possible to remove them,
but didn't want to check in this PR).

Add devnet in NETWORK config

---

src/kakarot/instructions/memory_operations.cairo
tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol
tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py

Not able to SSTORE the same variable several times in a transaction.
Works

Fix SSTORE not working more than one time in a tx

---

scripts/constants.py
scripts/utils/starknet.py

The project relies on a `scripts/utils/starknet.py` set of tools for interacting with Starknet(-like) network(s).
This module is indeed a "hidden package" originated from Starksheet devX and shared in different projects.
This PR just updates it to the latest improvements brought elsewhere.
I've never considered making this a real python packaging because it always introduces some burden
when it comes to maintainability and easy adaption to this ever changing dev environment.
Furthermore, the gold standard will soon be to use `starkli` so I'm not sure it's worth doing it rn.
That being said, if reviewers feels like it's a good idea, I can consider it!

Update starknet utils to latest

---

scripts/deploy_kakarot.py

Time spent on this PR: 0
- Allow deployer account to be deployed on custom networks

dev: add custom deployment network

---

docs/CONTRIBUTING.md

docs: update contributing.md

---

scripts/constants.py
scripts/deploy_kakarot.py

Time spent on this PR: 0
Resolves #705 
- Use `custom_rpc` network name for custom RPC configuration i.e. when `STARKNET_NETWORK` is not set
- Fix code smell on the networks which deployer is being deployed on

dev: use explicit name for custom network

---

docs/general/kakarot_components.md

Time spent on this PR: 1 Day 
This PR resolves #629 
- Docs had some mentions of `Account Registry`
- No confusion on account registry's implementation

Remove Account Registry from

---

README.md
tests/end_to_end/bytecodes.py

docs: fix link to thoth callgraph and introduction
-
-
-

docs: fix link to thoth callgraph and introduction

---

tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py

Resolves #727 
- add failing tests for deployment of contract account when there is no return data
- mark as skip and TODO

dev: add failing test for deployment of contract account when there is no return data

---

.gitignore
foundry.toml
tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.s.sol

No way to easily run some forge script to deploy into a real EVM
Updated config to target anvil by default and an example script.
Note: once the end to end refacto is done, I think that we'll update the structure of the solidity project

Add an example forge script for easy test to anvil

---

docs/general/decode_a_cairo_trace.md

docs: add decode cairo trace markdown file

---

scripts/constants.py

Adds erc20 to the list of compiled contracts.
Time spent on this PR: 0.01 day
ERC20 is not compiled when running `make build`.
Resolves #NA
`make build` will also compile an erc20 contract.

feat: add erc20 to compiled contracts

---

tests/integration/ef_tests/test_ef_blockchain_tests.py

fix: fix evm_to_starknet_address mapping

---

scripts/ef-tests/debug.py

Resolves #NA
Python script is available to deploy a ef-test on anvil and then debug this test to see the evm state after each opcode execution.

dev: python script to deploy ef-test on anvil

---

src/kakarot/constants.cairo
src/kakarot/evm.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/precompiles/precompiles.cairo
src/kakarot/state.cairo
tests/src/kakarot/instructions/test_block_information.cairo
tests/src/kakarot/instructions/test_block_information.py

Time spent on this PR: 1 day
Block Information doesn't raise OOG
Resolves #785 
Raise OOG.

Add OOG to BlockInformation

---

src/kakarot/execution_context.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/memory.cairo
src/kakarot/stack.cairo
tests/src/kakarot/accounts/eoa/mock_kakarot.cairo

Some functions declare unnecessary implicit args, which is not free.
Removed some unnecessary ones.

Remove unused implicit args

---

.gitignore
scripts/ef_tests.py

Add script to plot steps evolution

---

src/kakarot/evm.cairo
src/kakarot/instructions/logging_operations.cairo

No OOG
Resolves #799
OOG + refacto.

Add OOG for LOG operations

---

src/kakarot/precompiles/ec_recover.cairo

Time spent on this PR: 0.6 day
The point at infinity is not handled.
Resolves #NA
An invalid return by `recover_public_key` is handled.

fix: add handling of invalid public key

---

src/kakarot/instructions/environmental_information.cairo
src/utils/uint256.cairo
tests/src/kakarot/instructions/test_environmental_information.cairo
tests/src/kakarot/instructions/test_environmental_information.py

Resolves #796 
- follow https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L392

fix: fix empty account in extcodehash

---

src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/environmental_information.cairo

Time spent on this PR: 0.1day
Resolves #812 
basefee returns gas price

fix: basefee returns gasprice

---

scripts/ef-tests/debug.py

Block timestamp is not set to the correct ef-tests block.
Resolves #NA
Block timestamp is correctly set.

fix: ef-tests debug script

---

poetry.lock
pyproject.toml
scripts/ef-tests/debug.py

The debug scripts displays the command to run.
The debug script first run the tx and displays the output so as to be easier to detect failed/OOG tx.
The command is also copied into the clipboard.

Run tx in anvil debug script

---

src/kakarot/instructions/environmental_information.cairo

Resolves #813
Probably left from static gas refacto.
No unused code.

Remove unused ensure_lenght

---

.github/workflows/ci.yml

Copied the step from ef-tests.
The tests are supposed to be run with the python script wrapper to extract the data.

Fix resources CI

---

scripts/ef-tests/debug.py

The timestamp for anvil is set to the genesis block timestamp.
Resolves #NA
Set the timestamp to the current block timestamp.

fix timestamp 

---

src/kakarot/errors.cairo
src/kakarot/execution_context.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/utils/bytes.cairo
src/utils/eth_transaction.cairo
src/utils/utils.cairo
tests/src/utils/test_bytes.cairo
tests/src/utils/test_bytes.py

Following partial #840 merged after CI went ✅

Refacto casting utils

---

src/kakarot/evm.cairo
src/kakarot/execution_context.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/kakarot.cairo
src/kakarot/precompiles/modexp.cairo
src/utils/bytes.cairo
src/utils/rlp.cairo
src/utils/utils.cairo
tests/src/utils/test_bytes.cairo
tests/src/utils/test_bytes.py

Keep working on this, following the merge of https://github.com/kkrt-labs/kakarot/pull/841

Refacto casting utils (ter)

---

.github/workflows/ci.yml

Time spent on this PR: 0.01 day

fix: add KAKAROT_VERSION in ef-tests CI run

---

.github/workflows/ci.yml

Compute resources even when test fails

---

.github/workflows/deployments.yml
docker/deployer/Dockerfile

The deploy workflow only has the read-all permissions.
Resolves #NA
Deploy can now write the packages.

fix: write access to packages

---

solidity_contracts/src/PlainOpcodes/PlainOpcodes.sol
src/kakarot/instructions/stop_and_math_operations.cairo
tests/end_to_end/PlainOpcodes/test_plain_opcodes.py

Fix MULMOD doesn't handle mod = 0

---

src/kakarot/state.cairo
tests/src/kakarot/test_state.cairo
tests/src/kakarot/test_state.py

- Implementation of an `is_account_alive` function required for coherent gas accounting in `call` and `selfdestruct` opcodes
-
-

feat: is_account_alive

---

.trunk/trunk.yaml
README.md

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/877)

chore: activate trunk pre-push hook

---

scripts/utils/kakarot.py
src/kakarot/accounts/eoa/library.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/kakarot.cairo
tests/end_to_end/PlainOpcodes/test_plain_opcodes.py

Resolves: #870
- Return gas_used in eth_send_transaction and eth_call
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/876)

feat: return gas_used in eth_call and eth_send_transaction

---

README.md
tests/fixtures/starknet.py
tests/utils/reporting.py

No working profiling for tests using starknet.testing object.
Generate `.pb.gz` file as well
Usage:
- put the function call in a `with traceit.context("a given name"):`
- run the test with `--profile-cairo`
- for example
```
with traceit.context("contract_account"):
await contract_account.write_bytecode(bytecode).execute(
caller_address=kakarot.contract_address
)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/879)

Fix profiling for test using starknet

---

blockchain-tests-skip.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/881)

Update skip file

---

blockchain-tests-skip.yml
src/kakarot/evm.cairo
src/kakarot/gas.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/precompiles/ripemd160.cairo
src/kakarot/state.cairo
tests/src/kakarot/precompiles/test_ripemd160.py
tests/src/kakarot/test_gas.cairo
tests/src/kakarot/test_gas.py
tests/src/kakarot/test_state.cairo
tests/src/kakarot/test_state.py

Time spent on this PR: 2d
- Adds coherent gas accounting in call opcode, not done the rest yet
- Fixed gas utils
- Fixed finalization of state during account copys when encountering null pointers
- Added check in sstore for gas stipend requirement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/880)

refactor: call opcode w/ gas

---

README.md

i have updated the contributors link and make clickable also added Kakarot official discord.
Time spent on this PR: 0.5 day
you can find the official Kakarot discord and when you click on Contributors it takes you to the right page.
-you can find the official Kakarot discord.
-when you click on Contributors it takes you to the right page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/884)

Update kakarot links

---

blockchain-tests-skip.yml
src/kakarot/instructions/system_operations.cairo

Resolves #887 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/894)

feat: gas accounting call opcodes

---

src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/interpreter.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/model.cairo
src/kakarot/precompiles/precompiles.cairo
src/utils/eth_transaction.cairo
tests/fixtures/EVM.cairo
tests/src/kakarot/accounts/eoa/mock_kakarot.cairo
tests/src/kakarot/precompiles/test_precompiles.cairo
tests/src/utils/test_eth_transaction.cairo
tests/utils/helpers.cairo

Resolves #773 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/895)

refactor: use u256 for value type

---

tests/fixtures/starknet.py
tests/src/kakarot/SyscallHandler
tests/src/kakarot/instructions/test_block_information.cairo
tests/src/kakarot/instructions/test_block_information.py
tests/src/kakarot/instructions/test_duplication_operations.cairo
tests/src/kakarot/instructions/test_duplication_operations.py
tests/src/kakarot/instructions/test_environmental_information.cairo
tests/src/kakarot/instructions/test_environmental_information.py
tests/src/kakarot/test_account.cairo
tests/src/kakarot/test_account.py
tests/src/kakarot/test_evm.cairo
tests/src/kakarot/test_evm.py
tests/src/kakarot/test_execution_context.cairo
tests/src/kakarot/test_execution_context.py
tests/src/kakarot/test_state.cairo
tests/src/kakarot/test_state.py
tests/utils/syscall_handler.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/896)

Mock syscalls in tests

---

scripts/ef-tests/debug.py

Debug script fails with access list transactions.
Resolves #NA
Fixed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/905)

fix: handle access list tx

---

src/utils/eth_transaction.cairo
src/utils/rlp.cairo
tests/fixtures/starknet.py
tests/src/utils/test_rlp.cairo
tests/src/utils/test_rlp.py
tests/utils/helpers.py
tests/utils/hints.py

Time spent on this PR: 0.7d
Resolves #907
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/908)

feat: enable recursive RLP-list decoding

---

scripts/constants.py
scripts/deploy_kakarot.py
scripts/utils/kakarot.py
src/backend/starknet.cairo
src/kakarot/accounts/eoa/library.cairo
src/kakarot/constants.cairo
src/kakarot/precompiles/precompiles.cairo
src/utils/eth_transaction.cairo
tests/end_to_end/bytecodes.py
tests/fixtures/EVM.cairo
tests/src/utils/test_eth_transaction.cairo
tests/src/utils/test_eth_transaction.py
tests/utils/helpers.py
tests/utils/syscall_handler.py

Time spent on this PR: 0.15
A constant _chain id_ is hard coded in the codebase. However, we need to be able to update it easily for
several testnet versions.
Resolves #911
Use the underlying Starknet chain id.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/920)

Use Starknet chain id

---

scripts/constants.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/922)

Fix chain_id is undefined in unit tests

---

blockchain-tests-skip.yml
scripts/utils/kakarot.py
src/kakarot/account.cairo
src/kakarot/accounts/eoa/library.cairo
src/kakarot/gas.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/interpreter.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/state.cairo
src/utils/eth_transaction.cairo
tests/end_to_end/test_kakarot.py
tests/fixtures/EVM.cairo
tests/src/kakarot/test_state.cairo
tests/src/kakarot/test_state.py
tests/src/utils/test_eth_transaction.cairo
tests/utils/hints.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/924)

feat: cache access list

---

tests/end_to_end/test_kakarot.py

Adding a test that shows we can run eth_call to simulate a funds transfer!
TL;DR -> all good! if an error occurs for eth_call for a transfer, it's on the RPC!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/927)

feat: add a test to show eth_call

---

.github/workflows/deployments.yml
.github/workflows/release.yml
docker/deployer/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/933)

ci: added release workflow

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/952)

ci: add artifacts on release

---

tests/fixtures/starknet.py
tests/src/backend/test_starknet.cairo
tests/src/backend/test_starknet.py
tests/src/kakarot/test_memory.cairo
tests/src/kakarot/test_memory.py
tests/src/kakarot/test_stack.cairo
tests/src/kakarot/test_stack.py
tests/src/utils/test_eth_transaction.py
tests/utils/serde.py

Time spent on this PR: 0.6
Resolves #941
Resolves #942
Serialized.
Also a default serializer has been introduced that should be able to handle basic struct even when they are not defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/953)

Serialize Stack, Memory and Environment

---

tests/src/utils/test_eth_transaction.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/955)

Unskip test txs with empty to

---

blockchain-tests-skip.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/957)

Unskip after coinbase + basefee

---

.gitignore
.trunk/trunk.yaml
blockchain-tests-skip.yml
poetry.lock
pyproject.toml
scripts/artifacts.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/958)

Add function to pull and plot ef test

---

blockchain-tests-skip.yml
src/kakarot/interpreter.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/968)

feat: validate initcode len for deploy txs

---

.github/workflows/ci.yml
blockchain-tests-skip.yml
src/kakarot/evm.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/interpreter.cairo
src/utils/utils.cairo

-
- fixed calldata word count
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/971)

fix: create opcodes gas and jumpdest execution

---

scripts/constants.py
scripts/utils/starknet.py
src/kakarot/events.cairo
src/kakarot/kakarot.cairo
tests/end_to_end/conftest.py
tests/end_to_end/test_kakarot.py
tests/fixtures/replace_class.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/969)

Make kakarot upgradable

---

blockchain-tests-skip.yml
src/kakarot/instructions/system_operations.cairo

- Fixes wrong computation of nonce overflow 
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/976)

fix: CREATE high nonce

---

blockchain-tests-skip.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/978)

skip ef tests

---

src/kakarot/instructions/system_operations.cairo
src/kakarot/interpreter.cairo
src/kakarot/state.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/977)

fix: same-address transfers, fix: withdraw gas value for execution

---

blockchain-tests-skip.yml
src/kakarot/gas.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/981)

fix:saturated memory cost

---

.github/workflows/ci.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/990)

ci: replace install katana commands with binary install

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/992)

Fix katana cache

---

blockchain-tests-skip.yml
src/kakarot/instructions/environmental_information.cairo

**DEPENDS ON #982**
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/986)

fix: returndatacopy with high offsets

---

scripts/utils/starknet.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/993)

Remove useless int to hex parsing

---

blockchain-tests-skip.yml
src/kakarot/instructions/system_operations.cairo
src/kakarot/interpreter.cairo

**DEPENDS ON #982**
Time spent on this PR: 0.4d
- Fixes restoration of the previous state upon CREATE failure. Previous implementation did not take into account the possibliity that the commitment of the code would fail.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/985)

fix: create restores correct state upon failure

---

scripts/constants.py
scripts/utils/starknet.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/994)

Add kakarot config and fix max_fee is 0

---

scripts/utils/kakarot.py
src/kakarot/interfaces/interfaces.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
tests/end_to_end/test_kakarot.py
tests/utils/contracts.py

Resolves #996 
BREAKING CHANGES TO API
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/997)

feat: add nonce to eth_call

---

.gitignore
deployments/kakarot-sepolia/declarations.json
deployments/kakarot-sepolia/deployments.json
scripts/constants.py
scripts/deploy_kakarot.py
scripts/utils/kakarot.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1002)

Update deploy script to upgrade kakarot if already deployed

---

blockchain-tests-skip.yml
src/kakarot/interpreter.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1003)

fix: sender balance validation

---

blockchain-tests-skip.yml
src/kakarot/gas.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/logging_operations.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/model.cairo
tests/src/kakarot/test_gas.cairo
tests/utils/serde.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1004)

fix: memory expansion call/create opcodes

---

blockchain-tests-skip.yml
scripts/utils/kakarot.py
src/kakarot/accounts/eoa/library.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/interpreter.cairo
tests/end_to_end/test_kakarot.py
tests/src/kakarot/test_kakarot.py
tests/utils/constants.py

Time spent on this PR: 0.4d
- Add proper EIP-1159 validation on block gas / tx gas / account value
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1010)

fix: eip1559 proper validation

---

blockchain-tests-skip.yml
src/kakarot/instructions/system_operations.cairo

Closes #1017
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1018)

fix: call depth

---

scripts/utils/kakarot.py

Resolves #1019 
Context:
- `get_eoa` is in kakarot.py file
- kakarot.py file uses toml package
- deploy_kakarot.py uses get_eoa
- toml is called in the deployer docker image
- toml is a dev dep, and is not available in the docker image
- fail ⚠️
Solutions:
- split kakarot.py in order to not try to import toml for the following functions: `get_eoa` and the ones it uses (~5 in the same file) => cleaner but overkill for 1 dependency
- add toml as real dependency => quick and dirty but fast
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1020)

make toml available to deployer docker imge

---

src/kakarot/gas.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1035)

chore: remove repetitive word

---

pyproject.toml
src/kakarot/constants.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/interpreter.cairo
tests/end_to_end/bytecodes.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1033)

feat: mcopy

---

deployments/kakarot-sepolia/declarations.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1024)

commit upgrade of kakarot

---

poetry.lock
pyproject.toml
src/backend/starknet.cairo
src/kakarot/account.cairo
src/kakarot/accounts/contract/contract_account.cairo
src/kakarot/accounts/contract/library.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/interpreter.cairo
src/kakarot/model.cairo
tests/end_to_end/PlainOpcodes/test_plain_opcodes.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1032)

feat: selfdestruct cancun

---

pyproject.toml
src/kakarot/constants.cairo
src/kakarot/instructions/block_information.cairo
src/kakarot/interpreter.cairo
tests/end_to_end/bytecodes.py
tests/src/kakarot/instructions/test_block_information.py
tests/utils/constants.py

- Implements the `blobbasefee` opcode. Since we don't support blob txs, always returns 0.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1037)

feat: blobbasefee (0x4a)

---

tests/src/kakarot/instructions/test_block_information.cairo
tests/src/kakarot/instructions/test_block_information.py

- remove dead code introduced by #1048 
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1050)

chore: remove dead code

---

kakarot_scripts/constants.py
kakarot_scripts/utils/kakarot.py
kakarot_scripts/utils/starknet.py

Time spent on this PR: 0.5 day
Missing sepolia to the list of testnets
Resolves #NA
Add sepolia to the list of testnets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1051)

dev: add sepolia to the list of testnets

---

kakarot_scripts/constants.py
kakarot_scripts/deploy_kakarot.py
src/kakarot/interfaces/interfaces.cairo
src/kakarot/precompiles/precompiles.cairo

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1057)

dev: Precompiles -> Cairo1Helpers

---

docs/general/accounts.md

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1056)

docs: accounts

---

.github/workflows/ci.yml
src/kakarot/instructions/block_information.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/sha3.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/precompiles/precompiles.cairo
src/kakarot/storages.cairo
tests/fixtures/EVM.cairo
tests/src/kakarot/instructions/test_environmental_information.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1081)

dev: rename precompiles class

---

.github/workflows/ci.yml

Introduced in #1081, CI needs to point to main once EF-Test branch is merged
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1082)

dev: point ef-tests to main

---

deployments/kakarot-sepolia/declarations.json
deployments/kakarot-sepolia/deployments.json
kakarot_scripts/constants.py

Time spent on this PR: 0.01day
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1089)

deployment: kakarot v0.6.2 testnet sepolia

---

poetry.lock
pyproject.toml

0.13.1 introduces the range_check96 builtin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1096)

Update cairo-lang to 0.13.1

---

.devcontainer/devcontainer.json
tests/fixtures/starknet.py

Fix devcontainer file
Add new builtin in the python test runner (no impact so far, but to have the list complete)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1098)

Fix devcontainer

---

tests/fixtures/starknet.py

Time spent on this PR: 0.5 H
Resolves #1115
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1120)

dev: add 4m step limit to cairo runner

---

Makefile
kakarot_scripts/utils/kakarot.py

- bump Katana to `v0.6.1-alpha.4`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1126)

bump Katana to `v0.6.1-alpha.4`

---

deployments/kakarot-sepolia/declarations.json
deployments/kakarot-sepolia/deployments.json
kakarot_scripts/constants.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1119)

deploy kakarot onto kakarot sepolia

---

deployments/kakarot-sepolia/declarations.json

Time spent on this PR: 10mn
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1131)

upgrade kakarot to 0.7.4

---

Makefile

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1132)

Bump katana to v0.7.0-alpha.0

---

blockchain-tests-skip.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1142)

fix: skipfile

---

blockchain-tests-skip.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1143)

fix skipfile (2)

---

Makefile

Kakarot pulls the latest release of SSJ.
Resolves #NA
Kakarot pulls a fixed release of SSJ.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1158)

fix release ssj

---

kakarot_scripts/utils/fetch_outdated_eoas.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1163)

script: fetch oudated eoas

---

README.md

Time spent on this PR: 1h
Resolves #1165
fix readme's `docs/supported_opcodes.md` link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1166)

fix: docs/supported_opcodes.md missing

---

src/kakarot/kakarot.cairo
src/kakarot/library.cairo
tests/end_to_end/test_kakarot.py

feat: set account bytecode-nonce from kakarot
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1174)

feat: set account bytecode-nonce from kakarot

---

src/kakarot/errors.cairo
src/kakarot/interpreter.cairo
src/kakarot/kakarot.cairo
src/kakarot/library.cairo
src/kakarot/precompiles/kakarot_precompiles.cairo
src/kakarot/precompiles/precompiles.cairo
src/kakarot/storages.cairo
tests/end_to_end/CairoPrecompiles/Pragma/test_pragma_precompile.py
tests/end_to_end/CairoPrecompiles/test_cairo_precompiles.py
tests/src/kakarot/precompiles/test_precompiles.cairo
tests/src/kakarot/precompiles/test_precompiles.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1177)

feat: add whitelisting for pragma precompile caller

---

.github/workflows/ci.yml
kakarot_scripts/utils/kakarot.py
src/kakarot/accounts/library.cairo

Signature was extended to length of 6 assuming signature would impact the hash computation.
Resolves #1183
Reverted #1162
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1184)

revert: signature extension

---

src/kakarot/account.cairo
tests/end_to_end/test_account.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1194)

revert: disable auto upgrades

---

tests/src/kakarot/accounts/test_contract_account.cairo
tests/src/kakarot/accounts/test_contract_account.py

Time spent on this PR: 1 day
Resolves #1186 
-New unit test for set_nonce
-New unit test for set_implementation
-New cairo func called test__set_nonce
-New cairo func called test__set_implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1202)

Adding Unit tests for set_nonce and set_implementation

---

src/kakarot/kakarot.cairo
src/kakarot/library.cairo
tests/end_to_end/conftest.py
tests/end_to_end/test_account.py
tests/end_to_end/test_kakarot.py

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1207)

feat: add upgrade account entrypoint to Kakarot

---

docker/deployer/Dockerfile

to a relevant issue. -->
Resolves #NA
Add the cairo 1 contracts in the deployer (otherwise we cannot use the deployer in a docker compose with Katana).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1208)

fix: add cairo 1 contract in deployer

---

src/kakarot/instructions/stop_and_math_operations.cairo
tests/src/kakarot/instructions/test_stop_and_math_operations.cairo
tests/src/kakarot/instructions/test_stop_and_math_operations.py

Resolves #1185
- solves the issue with INVALID that was falling back to LT
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1212)

fix: invalid opcode in math operations

---

tests/src/kakarot/test_kakarot.cairo
tests/src/kakarot/test_kakarot.py

Resolves #1201
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1211)

tests: add kakarot entrypoints tests

---

docker/deployer/Dockerfile

- Add scarb to the deployer in order to compile the Cairo1 pragma contract.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1216)

fix: add scarb to the deployer

---

tests/fixtures/starknet.py
tests/utils/coverage.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1221)

Remove dead code for coverrage

---

solidity_contracts/src/PlainOpcodes/PlainOpcodes.sol
solidity_contracts/tests/PlainOpcodes.t.sol
tests/end_to_end/PlainOpcodes/test_plain_opcodes.py

Resolves #1092
- adds a keccak test end to end 
for an input length of 20000 the step count is 3253621
- fix a failing test in PlainOpcodes.t.sol
- better separator in PlainOpcodes.t.sol
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1235)

dev: test keccak end-to-end

---

docker/deployer/Dockerfile
kakarot_scripts/utils/kakarot.py
kakarot_scripts/utils/l1.py
poetry.lock
pyproject.toml

Updates the dockerfile with the required changes:
- Make solidity_contracts available in docker image
- Move toml from dev-dependency to regular dependency
- Remove vyper artifacts (no longer required)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1250)

dev: update dockerfile

---

src/backend/starknet.cairo
src/kakarot/interpreter.cairo
src/kakarot/precompiles/kakarot_precompiles.cairo
src/kakarot/precompiles/precompiles.cairo
src/kakarot/precompiles/precompiles_helpers.cairo
tests/src/kakarot/precompiles/test_precompiles.cairo
tests/src/kakarot/precompiles/test_precompiles.py
tests/utils/syscall_handler.py

- Deploys a SN account for a caller of a Cairo contract if its account is not deployed on starknet already.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1253)

feat: deploy starknet account if CairoLib caller is not deployed

---

README.md

Time spent on this PR: 5min
Kakarot banner with fixed height creates distorted image depending on screen resolution.
- Changes fixed height to fixed width, banner is not distorted anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1272)

fix: enforce width on kakarot banner img

---

src/backend/starknet.cairo
src/kakarot/account.cairo
src/kakarot/accounts/account_contract.cairo
src/kakarot/accounts/library.cairo
src/kakarot/evm.cairo
src/kakarot/gas.cairo
src/kakarot/instructions/environmental_information.cairo
src/kakarot/instructions/memory_operations.cairo
src/kakarot/instructions/push_operations.cairo
src/kakarot/instructions/system_operations.cairo
src/kakarot/interpreter.cairo
src/kakarot/memory.cairo
src/kakarot/precompiles/blake2f.cairo
src/kakarot/precompiles/kakarot_precompiles.cairo
src/kakarot/precompiles/precompiles.cairo
src/kakarot/precompiles/precompiles_helpers.cairo
src/kakarot/precompiles/ripemd160.cairo
src/utils/eth_transaction.cairo
src/utils/rlp.cairo
src/utils/uint256.cairo
src/utils/utils.cairo

Resolves #1262
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1287)

opti: replace is_le by is_nn

---

src/kakarot/instructions/stop_and_math_operations.cairo
tests/src/kakarot/instructions/test_stop_and_math_operations.py

No overflow check on uint256_mul for BYTE
Resolves #1260
Check for overflow on uint256_mul for BYTE
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1288)

fix: check overflow on uint256_mul for BYTE

---

tests/utils/hints.py

Time spent on this PR: 0.05
No raise if hint is not found
Now raises if the patch doesn't do anything
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1304)

Raise in patch_hint if hint is not found

---

.github/workflows/ci.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1310)

ci: point ef-test to main

---

tests/src/kakarot/precompiles/test_ec_recover.py

Resolves #1308 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1320)

 refactor: remove dead code in test_should_return_evm_address_in_bytes32

---

tests/src/kakarot/precompiles/test_ec_recover.py

Resolves #1308 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1321)

 refactor: remove dead code in test_should_return_evm_address_in_bytes32 (new)

---

.github/workflows/ci.yml
src/backend/starknet.cairo
src/kakarot/account.cairo

Resolves #1312
`Kakarot` address is taken into account for address computation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1330)

fix: deploy_from_zero to FALSE

---

src/kakarot/accounts/library.cairo
src/kakarot/instructions/memory_operations.cairo
tests/src/kakarot/accounts/test_account_contract.py

Resolves #1316
Overflow checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1329)

bug: missing overflow checks effective gas price calculation

---

src/utils/array.cairo

Resolves #1336
- `let (local rev: felt*) = alloc();` 
- `let dst = cast([fp], felt*);`
have been removed:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1340)

remove unnecessary reference

---

src/kakarot/interfaces/interfaces.cairo

Resolves #1291 
execute_from_outside is added to interface of IAccount
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1343)

feat: add execute_from_outside to interface

---

src/kakarot/accounts/library.cairo
tests/src/kakarot/accounts/test_account_contract.py

Resolves #1347 
Account_jumpdests_initialized is removed from storage variables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1348)

refactor: remove Account_jumpdests_initialized

---

src/kakarot/accounts/account_contract.cairo
src/kakarot/accounts/library.cairo
src/kakarot/interfaces/interfaces.cairo
tests/fixtures/uninitialized_account_fixture.cairo

Resolves #1332
Version is removed from account contract
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1349)

refactor: remove account version

---

docs/SECURITY.md

Link fix Update SECURITY
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1345)

Update twitter to x link in README

---

Makefile
kakarot_scripts/constants.py
kakarot_scripts/utils/kakarot.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1380)

Add a relayer pools to the config

---

src/kakarot/instructions/system_operations.cairo

Resolves #1389
No refunds are applied if the call reverted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1395)

fix: call gas refund only if success

---

.github/workflows/release.yml

- Installs scarb in the release workflow, required in `make build`
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1401)

fix: install scarb in release yml

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1406)

Fix venv not cached

---

.github/workflows/nightly-fuzzing.yml
poetry.lock
tests/conftest.py
tests/src/kakarot/test_kakarot.py

Resolves #1403
- A nightly run is triggered with [schedule](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule) at 0:20 UTC for unit test with 1500 examples for hypothesis
- CI runs is decreased to 100 examples
- refactoring of a few patches (30% faster on 1000 example for `test_raise_gas_limit_too_high`)
- update of hypothesis packages: should increase perfs for binary (see [changelog here](https://hypothesis.readthedocs.io/en/latest/changes.html))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1407)

ci: nightly fuzzing

---

codecov.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1408)

dev: Lower codecov precision

---

solidity_contracts/src/L1L2Messaging/L1KakarotMessaging.sol
solidity_contracts/tests/L1KakarotMessage.t.sol

- add foundry unit test for L1KakarotMessaging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1416)

test: L1KakarotMessaging

---

.github/workflows/ci.yml
blockchain-tests-skip.yml

temp PR to run the CI against an updated branch of EF-Tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1418)

dev: update skipped-tests for ef-tests-14-1

---

src/kakarot/accounts/account_contract.cairo
src/kakarot/interfaces/interfaces.cairo
src/kakarot/library.cairo
tests/src/kakarot/accounts/test_account_contract.cairo
tests/src/kakarot/accounts/test_account_contract.py
tests/src/kakarot/test_kakarot.cairo
tests/src/kakarot/test_kakarot.py

Resolves #1424
- Adds a new entrypoint `replace_class` to the account contract to replace it's class. This will be used when migrating from CairoZero to Cairo 
- Add a test to verify we can upgrade accounts arbitrarly from Kakarot.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1428)

feat: replace account class

---

.github/workflows/ci.yml
solidity_contracts/tests/L1KakarotMessage.t.sol

- fix test
- run forge test in ci
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1434)

chore: run forge test in ci

---

kakarot_scripts/utils/kakarot.py
src/kakarot/interfaces/interfaces.cairo
src/kakarot/kakarot.cairo
tests/end_to_end/test_kakarot.py
tests/fixtures/EVM.cairo

- Remove this entrypoint, deprecated in favor of `get_starknet_address`
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1436)

feat: remove 'compute_starknet_address'

---

blockchain-tests-skip.yml

- Update skipfile with latest changes.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1440)

dev: update skipfile

---

blockchain-tests-skip.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1443)

dev: unskip tests

---

.github/workflows/nightly-fuzzing.yml

-  nightly tests use uv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1453)

ci: nightly tests use uv

---

.github/workflows/ci.yml
Makefile

Related https://github.com/kkrt-labs/kakarot-rpc/pull/1422
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1459)

bump katana to v1.0.0-alpha.13

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1467)

bump katana to `v1.0.0-alpha.14`

---

.github/workflows/cairo-zero-release.yml

-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1480)

ci: release use uv

---

cairo_zero/kakarot/interfaces/interfaces.cairo
tests/end_to_end/test_kakarot.py

Resolves #1471
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1491)

fix: add missing func to kakarot interface

---

.gitmodules
remappings.txt
solidity_contracts/src/Kakarot/Coinbase.sol
solidity_contracts/src/UniswapV2Router/libraries/UniswapV2Library.sol
tests/end_to_end/Kakarot/test_coinbase.py

Resolves #1488
Coinbase use Ownable2Step from OZ with version 5.0.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1494)

feat: Ownable2Step coinbase

---

docker/deployer/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1511)

dev: add cargo binaries to PATH in Dockerfile

---

pyproject.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1549)

Add missing mark

---

kakarot_scripts/setup/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1550)

Fix foundryup not found

---

.github/workflows/cairo-zero-ci.yml
.github/workflows/ssj-build.yml
.github/workflows/ssj-ci.yml
.github/workflows/ssj-ef-tests.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1578)

chore: bump artifact action

---

cairo_zero/kakarot/constants.cairo
cairo_zero/kakarot/library.cairo

Fees are payed on L1 in the starknet messaging contract.
Users should not pay a second time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1584)

[KGA-70] fix: handle_l1_message gas price set to 0

---

README.md

Hello. Added links that were missing in the documentation
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1607)

Docs:  Update README

---

cairo_zero/kakarot/precompiles/kakarot_precompiles.cairo
docs/general/cairo_precompiles.md

adds code doc on the kakarot precompiles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1610)

docs: kakarot precompiles

---

kakarot_scripts/utils/deploy_oz.py

Fix the randbits to generate the private key of the correct size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1614)

fix: private key randbits on deploy_oz script

---

cairo_zero/kakarot/precompiles/precompiles.cairo
cairo_zero/kakarot/state.cairo

https://github.com/code-423n4/2024-09-kakarot-findings/issues/128

[KGA-101] Qa report 128

---

cairo_zero/kakarot/instructions/block_information.cairo

fix: off by one blockHash

---

cairo_zero/kakarot/interfaces/interfaces.cairo

fix: Kakarot interface
