- docs/supported_opcodes.md
- src/kakarot/instructions.cairo
- src/kakarot/instructions/comparison_operations.cairo
- tests/cases/003/shl/1.json
- tests/cases/003/shl/10.json
- tests/cases/003/shl/11.json
- tests/cases/003/shl/2.json
- tests/cases/003/shl/3.json
- tests/cases/003/shl/4.json
- tests/cases/003/shl/5.json
- tests/cases/003/shl/6.json
- tests/cases/003/shl/7.json
- tests/cases/003/shl/8.json
- tests/cases/003/shl/9.json
- tests/cases/003/shr/1.json
- tests/cases/003/shr/10.json
- tests/cases/003/shr/11.json
- tests/cases/003/shr/2.json
- tests/cases/003/shr/3.json
- tests/cases/003/shr/4.json
- tests/cases/003/shr/5.json
- tests/cases/003/shr/6.json
- tests/cases/003/shr/7.json
- tests/cases/003/shr/8.json
- tests/cases/003/shr/9.json
- tests/units/kakarot/test_basic.cairo
- tests/utils.cairo
Core:
- Add 0x1b opcode (shl)
- Add 0x1c opcode (shr)
- Add tests for shl and shr (directly from [EIP-145](https://eips.ethereum.org/EIPS/eip-145))
Non-core:
- Had to change the layout of tests a bit
- Had to update some helper functions to take `Uint256` as input instead of `felt`
Closes #51 
Closes #52
> feat: implement 0x1b and 0x1c (shl and shr)

- src/kakarot/instructions/arithmetic_operations.cairo
- src/kakarot/stack.cairo
- tests/units/kakarot/test_stack.cairo
- Pop N elements from the stack at once is now supported
> :sparkles: Implement stack pop_n

- Makefile
- src/kakarot/execution_context.cairo
- src/kakarot/instructions.cairo
- src/kakarot/instructions/arithmetic_operations.cairo
- src/kakarot/instructions/block_information.cairo
- src/kakarot/instructions/comparison_operations.cairo
- src/kakarot/instructions/duplication_operations.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/exchange_operations.cairo
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/push_operations.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/memory.cairo
- src/kakarot/stack.cairo
- tests/utils.cairo
Replace the print statements used inside the hints with a python logger
Right now the cairo programs are printing information using a print statement inside a hint
Issue Number: [126](https://github.com/sayajin-labs/kakarot/issues/126)
Now we are importing a python logger in the hint and setting the logs with an info level
> dev: Remove prints in the cairo files

- .github/workflows/test.yml
- Makefile
- README.md
- poetry.lock
- poetry.toml
- pyproject.toml
- requirements.txt
- tests/__init__.py
- tests/test_basic.py
- tests/units/instructions/test_arithmetic_operations.py
- tests/units/instructions/test_block_information.py
- tests/units/instructions/test_memory_operations.py
- tests/units/test_execution_context.py
- tests/units/test_memory.py
- tests/units/test_stack.py
Python dependencies are not locked to precise versions nor exaustives.
Python files don't have a consistent formatting.
- use [poetry](https://python-poetry.org/docs/) for deps management
- use [black](https://github.com/psf/black) for linting files
- use [isort](https://github.com/PyCQA/isort) for correctly sorting imports
Following the current documentation, I have decided to disable the virtualenv creation of `poetry` and let the user manage their own way of having a python3.9 working before installing the project.
> Use poetry for deps management and add python linter (black & isort)

- tests/cairo_files/instructions/test_block_information.cairo
- tests/units/instructions/test_block_information.py
Of the block information instructions, only CHAINID is unit tested.
All block information instructions have unit tests.
- Add tests for instructions timestamp, number, and gaslimit which are totally implemented
- Add tests for instructions coinbase, difficulty, and basefee which are implemented but actual values pushed to the stack appear to be stubs. Still, these functions affect the state (e.g. gas consumed) and should be tested IMO. When these instructions are changed to push different values the tests can be tweaked.
I've tried to conform to all code, git, and PR styles. Please let me know if anything should be adjusted.
> Add tests for remaining block information instructions

- pyproject.toml
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/memory.cairo
- src/utils/utils.cairo
- tests/cairo_files/instructions/test_memory_operations.cairo
- tests/cairo_files/test_memory.cairo
- tests/test_zk_evm.py
- tests/units/test_memory.py
The memory is not expanded on request, and consequent gas consumption is not taken into account.
#120 
A new `Memory.insure_length` has been created and used in mload and sha3.
It returns a new memory with sufficient length and gas cost (possibly 0) associated with this possible increase.
> Add memory expansion method and use it in sha3 and exec_mload

- src/kakarot/instructions/sha3.cairo
If the memory is expanded during sha3, it is not updated in the context.
Context is properly updated
> Add forgotten ExecutionContext.update_memory to sha3

- docs/supported_opcodes.md
- src/kakarot/instructions.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/memory.cairo
- src/utils/utils.cairo
- tests/test_zk_evm.py
Adding test cases to the opcode 0x39 led to 2 failures. The failures have been identified to be linked to corner cases in Memory.store_n and Helpers.slice_data. Such a corner case is for example when taking a slice with offset out of bound.
Issue Number: related to 98
Tests for the CODECOPY (0x39) opcode have been extended with more cases taking different code-paths.
Memory.store_n and Helpers.slice_data have been reimplemented to cover all cases.
Cases for slice_data:
1. slice fully overlaps with data:  data_offset + slice_len <= data_len
2. slice partially overlaps with data: data_offset < data_len < data_offset + slice_len
3. slice does not overlap with data: data_len <= data_offset
For Memory.store_n, the new memory is composed of 3 …
> Fix: Memory.store_n and Helpers.slice_data for border cases

- tests/test_zk_evm.py
Add test for CALLDATASIZE when CALLDATA is not empty.
Fix @abdelhamidbakhta comment https://github.com/sayajin-labs/kakarot/pull/146/files#r1004043872
Currently CALLDATASIZE test only tests that stack is empty with empty CALLDATA. That does not ensure that CALLDATASIZE works well with non empty CALLDATA even if the feature is coded.
We add a test with the value 11111111 as CALLDATA and ensure CALLDATASIZE returns the size : 1
> feat(tests): add tests for CALLDATASIZE and non empty calldata

- Makefile
- README.md
- docs/supported_opcodes.md
- src/kakarot/instructions.cairo
- src/kakarot/instructions/block_information.cairo
- tests/conftest.py
- tests/test_zk_evm.py
Issue Number: #87
Fixes: #87
- Format and rearrange Block Information opcodes accordingly
- 0x47 SELFBALANCE opcode implemented
- Get balance of currently executing contract by getting it from the execution context and querying its balance from the eth contract
- Add distinction among test cases for `test_execute` and `test_execute_at_address`
> Feat/add 0x47 SELFBALANCE opcode

- Makefile
We have an issue when running tests locally via makefile.
Makefile does not follow the new test architecture implemented by @ClementWalter 
Tests didn't fail on GitHub actions because we run all the tests
> fix(makefile) update path with new test architecture

- poetry.lock
- pyproject.toml
- scripts/check_resources.py
The `check_resources.py` script checks local test reports against the latest one from `main`.
The output of the dataframe in the log is truncated.
The output is not truncated anymore.
Furthermore, the command display stats not only for main but for all the branches with artifacts.
The command can also be used locally to fetch perf, even though no local artifacts exist.
There is still an open question regarding this hard limit on every resources used.
> Update check-resources to display all historical data and not only main

- .github/workflows/test.yml
- scripts/check_resources.py
The CI runs on `pull_request` and `pull_request_target`  target. This later is indeed useless though takes time and make the latest artifact of a branch not reliably the one computed on this branch.
The worklow simply runs on `pull_request`.
For new branches, `make resources-check` returns consistent metrics.
> Remove pull_request_target event

- src/kakarot/execution_context.cairo
- src/kakarot/instructions/logging_operations.cairo
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- src/kakarot/memory.cairo
- src/kakarot/model.cairo
- src/utils/utils.cairo
- tests/cairo_files/test_memory.cairo
- tests/integrations/test_zk_evm.py
- tests/utils/utils.cairo
- tests/utils/utils.py
Refactor memryo to use a dictionary of 128bit words.
Currently, memory is represented as an array, and is reallocated entirely on every write.
Memory writes and reads will go through a dictionary of packed 128bit words.
-
-
-
> Memory using dicts

- src/kakarot/memory.cairo
- src/utils/utils.cairo
- tests/integrations/test_cases/execute.py
Related to: https://github.com/orgs/sayajin-labs/projects/3/views/6?query=is%3Aopen+sort%3Aupdated-desc
Goal of this ticket is to remove the [SKIPPED test](https://github.com/sayajin-labs/kakarot/pull/304/files#diff-33071fb3d4629eb5c6c61cecfc36090d09f4f9b5c408e92088f1df2488cc97a1L994) about mstore.
Currently when there is an offset we increase the memory with the exact necessary size but normal behaviour should be to expand memory to next byte (see for example [evmjs implementation](https://github.com/ethereumjs/ethereumjs-monorepo/blob/985f2aa43c005573382b98423fcfd3bd368b2c8e/packages/evm/src/memory.ts#L30)
Current PR add a test and remove the skipping of the current one in mstore
> fix: fix mstore not ceiling to next byte when offset

- tests/integrations/test_zk_evm.py
in [erc20 integration test](https://github.com/sayajin-labs/kakarot/blob/main/tests/integrations/test_zk_evm.py#L76)
`await erc_20.mint(addresses[2], 0x164, caller_address=caller_addresses[1])`
we could improve readability using the '356' decimal value instead of 0x164
Issue Number: #273 
- the `0x164` was replaced with `356`
> refactor: manipulate decimal number in tests

- src/kakarot/accounts/contract/library.cairo
- tests/units/test_contract_account.py
The Account contract stores the bytecode of the contract as an array of felt, one byte per felt.
Issue Number: #239 
I have used bytes16 internal felt packing.
Is 16 better than 31? I've used this because of the `unsigned_div_rem` but maybe better to use bytes31 and Uint256 div.
May also be better to accept the packed bytecode in the constructor to avoid the cost of doing it in the contract.
Maybe to return packed felt as well and update the other functions accordingly.
This was a fast (and furious 🏁) quick look at the question to have a first estimate of potential gains.
> Use internal bytes16 storage, no external API change

- pyproject.toml
- tests/conftest.py
- tests/utils/utils.py
No profiling data
Profiling data for each test in pprof format when running tests with the `--trace-run` flag.
Generating profiling data is **slow** and consequently disabled by default! When you want to use the tool, just run the target test with `pytest <target test> --trace-run`
> Profiling data

- src/utils/utils.cairo
- tests/cairo_files/instructions/test_push_operations.cairo
- tests/cairo_files/test_utils.cairo
- tests/units/instructions/test_push_operations.py
- tests/units/test_utils.py
The bytes_i_to_uint256 was bugged with sequences of exactly 16 bytes.
Issue was caused by a [lower_or_equal]([`main...matthieuauger:kakarot:fix-bytes_to_uint256?expand=1`#diff-7125bfc485](https://github.com/sayajin-labs/kakarot/compare/main...matthieuauger:kakarot:fix-bytes_to_uint256?expand=1#diff-7125bfc4851cb1b3a82161b692339e996956180ec6a010a5f5dd7504ee97cef9)L59) used instead of a strict lower.
- First commit of the PR consists of adding tests for the function.
- Second commit is a refactoring of the function, simplying its implementation and improving naming
- Third commit is the actual bugfix
- Fourth commit is the re-enablement of the exec_push16 test that was blocked because of this bug
Fixed #333
> Add tests for bytes_i_to_uint256 method and fixes it for 16 bytes sequences

- src/kakarot/execution_context.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- src/utils/utils.cairo
- tests/integration/helpers/wrap_kakarot.py
- tests/unit/src/kakarot/instructions/test_comparison_operations.cairo
- tests/unit/src/kakarot/instructions/test_comparison_operations.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
`gas_limit` is passed as `0` to the sub contexts.
Resolves #[349](https://github.com/sayajin-labs/kakarot/issues/349)
- Adds `gas_limit` param to `execution_context.init_at_address()`, `kakarot.execute_at_address()`
- Limits the gas passed to sub-contexts to `min(remaining_gas, remaining_gas/64)`
> feat: use gas in CALLs opcodes #349

- src/kakarot/execution_context.cairo
- src/kakarot/instructions.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/library.cairo
- src/kakarot/model.cairo
- src/utils/utils.cairo
- tests/unit/helpers/helpers.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
- tests/unit/src/kakarot/test_execution_context.cairo
Resolves #97 
- a naming refactoring of the `ExecutionContext.intrinsic_gas_cost` -> `ExecutionContext.gas_price`
-  impl refactoring of 
- returns a felt of the cost, rather than an updated context
- computes the calldata costs
- a helper was created `Helpers.count_nonzeroes` that returns the count of the nonzeroes of the calldata array
- adds calldata costs to the `Constants.TRANSACTION_INTRINSIC_GAS_COST` 
- where previous uses of `ExecutionContext.compute_intrinsic_gas_cost`
- we call it and take the return value cost and pass that into `ExecutionContext.increment_gas_used` and use the context returned from that
> impl GASPRICE opcode (#97)

- .github/PULL_REQUEST_TEMPLATE.md
add an estimate of time spent for PRs so that contributors may help maintainers understand:
- how much time they spend on kakarot
- how they can help reduce friction / misunderstandings
- how they can help contributors
> docs: add an estimate of time spent for PRs

- .markdownlint.json
- README.md
- src/kakarot/execution_context.cairo
- src/kakarot/instructions.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
Markdown linting underlines images without alt text (ie. `![](path/to/file.png)`.
Rule is disabled so markdown linting does not show this as an error.
Time spent on this PR:  0.01 day
> Disable alt-text-required for markdown files

- src/kakarot/constants.cairo
- src/kakarot/execution_context.cairo
- src/kakarot/instructions.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/precompiles/datacopy.cairo
- src/kakarot/precompiles/precompile.cairo
- src/kakarot/precompiles/precompiles.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
- tests/unit/src/kakarot/precompiles/test_datacopy.cairo
- tests/unit/src/kakarot/precompiles/test_datacopy.py
call, staticcall, and delegatecall opcodes are not dispatching to precompile address 0x04, identity
Resolves #360 
Per earlier discussion with @ClementWalter 
- call, staticcall, and delegatecall opcodes are checking if address is within a precompile range
- if so, it delegates out to Precompile.run, which further dispatches for address to precompile implementation
- it passes the precompile implementation a 'stopped' context to which the implementation of a precompile is expected to update the return data with its result
Time spent on this PR:  1 day(s)
> Feature/precompile identity (#360)

- src/kakarot/instructions.cairo
- src/kakarot/model.cairo
Two opcodes are not used in the main jump table.
Call these opcodes instead of raise
It's over 9000!
> Update jumptable with latest opcodes

- pyproject.toml
- tests/fixtures/1_starknet.py
- tests/integration/conftest.py
- tests/integration/solidity_contracts/Counter/test_counter.py
- tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/integration/solidity_contracts/Solmate/test_erc20.py
- tests/integration/solidity_contracts/Solmate/test_erc721.py
When using a Solidity contracts in tests, state modifications are persisted across different tests.
Furthermore it's not possible to deploy to times the same contract (with different constructor args for example).
The `StarknetState` is cached in an `autouse` fixture; contracts can be deployed at module level, cached while state is reset after each test to its initial value.
I have moved some tests according to TODOs that were written herein (test concerning EXTCODECOPY inside test_erc20 and test_counter.
`Counter.sol` actually had no test so I wrote a bunch of them.
> Fix state update is persisted across tests

- tests/integration/helpers/wrap_kakarot.py
- tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
There is no way to test events emitted by a Solidity contract
Contract's events can be accessed with `contract.events.{event_name}` (one attribute per event).
This returns a list of emitted events in the last transaction; events are described as dict, eg.:
```
await token.approve(...)
assert token.events.Approval == [{
"owner": "0x..",
"spender": "0x...",
"value": 10,
}]
```
`web3.Contract` class already had `events.{event_name}` attributes. I've overridden this attribute to ease manipulation in our context.
> Parse events data for solidity contracts

- src/kakarot/instructions/system_operations.cairo
- src/kakarot/memory.cairo
- src/utils/utils.cairo
- tests/fixtures/4_blockhash_registry.py
- tests/integration/eoa/test_ethaa.py
- tests/integration/helpers/helpers.py
- tests/integration/solidity_contracts/Counter/Counter.sol
- tests/integration/solidity_contracts/Counter/test_counter.py
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/integration/solidity_contracts/Solmate/test_erc20.py
- tests/integration/solidity_contracts/Solmate/test_erc721.py
- tests/integration/solidity_contracts/UniswapV2/UniswapV2ERC20.sol
- tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_erc20.py
- tests/unit/helpers/helpers.cairo
- tests/unit/src/kakarot/accounts/registry/test_blockhash_registry.py
- tests/unit/src/kakarot/instructions/test_block_information.py
- tests/unit/src/kakarot/instructions/test_exchange_operations.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
- tests/unit/src/kakarot/precompiles/test_ec_recover.py
- tests/unit/src/kakarot/precompiles/test_precompiles.py
- tests/unit/src/kakarot/test_execution_context.py
- tests/unit/src/kakarot/test_instructions.py
- tests/unit/src/kakarot/test_stack.py
- tests/utils/errors.py
- tests/utils/signer.py
- tests/utils/uint256.py
The revert opcode does not load the revert reason but only returns a random number.
Resolves #416 
The reason is loaded as a bytes array. Only the short string is propagated with the `error_attr`.
We definitely need to fix REVERT (see #432) because this is close to a nightmare in terms of hard fixing to have something ok for testing.
> Load revert reason short string

- tests/fixtures/2_kakarot.py
- tests/integration/conftest.py
- tests/integration/helpers/helpers.py
- tests/integration/helpers/wrap_kakarot.py
- tests/integration/solidity_contracts/PlainOpcodes/PlainOpcodes.sol
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
Time spent on this PR: 1 day
Facing an error when testing Univ2Factory, I have eventually manage to isolate the error case in a `PlainOpcode.sol` test.
The error is illustrated in `class TestRequire` that is currently skipped (see also create issue https://github.com/sayajin-labs/kakarot/issues/439)
> Add tests for CREATE2 and require in PlainOpcodes

- tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
Random addresses are generated without setting the seed
These addresses may have a leading `0` nibble in bytes representation which breaks the `to_checksum_address`
Set seed
Generate 20 random bytes instead of a uint160.
> [Fix] Generate 20 bytes instead of a uint160 in Univ2Factory test

- tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
Time spent on this PR: 0.2 days
Random bytes drawing for TEST_ADDRESSES is not seedable.
The TEST_ADDRESSES are deterministically generated.
> fix: change RNG to allow seeding

- src/kakarot/accounts/contract/library.cairo
- src/kakarot/constants.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/library.cairo
- src/utils/utils.cairo
- tests/integration/bytecode/test_cases.py
- tests/integration/bytecode/test_kakarot.py
- tests/integration/conftest.py
- tests/integration/helpers/helpers.py
- tests/unit/helpers/helpers.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
Time spent on this PR: 1.75 days
The EVM address of a contract account is computed as follows:
```
// Generate EVM_contract address from the new cairo contract
// TODO: Use RLP to compute proper EVM address, see https://www.evm.codes/#f0
let (_, low) = split_felt(starknet_contract_address);
local evm_contract_address = 0xAbdE100700000000000000000000000000000000 + low;
```
Resolves #427 
also resolves #426 wrt create2 opcode
Create2's address is defined via
```
address = keccak256(0xff + sender_address + salt + keccak256(initialisation_code))[12:]
```
-
-
-
There is a current temporary split in deploy code, where create2 logic is handled separately from create. When both construct their address deterministically, the temporary refactor …
> Bugfix: create2 opcode should use deterministically derived evm contract address

- tests/integration/helpers/wrap_kakarot.py
Currently, one cannot `call` a solidity contract with a given `caller_address` as it makes the `call` an `execute`.
The `kwarg` `caller_address` is used anyhow with default value the one used on the corresponding functions, ie `0`.
> Fix caller_address uses only execute in tests

- poetry.lock
- pyproject.toml
- src/kakarot/instructions/system_operations.cairo
- src/utils/rlp.cairo
- src/utils/utils.cairo
- tests/integration/helpers/helpers.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
- tests/unit/src/kakarot/instructions/test_system_operations.py
Time spent on this PR: 1/2 day
Create opcode uses an easter egg 🥚 to determine the evm contract mapping.
Resolves #426 
The create opcode uses `CreateHelper.get_create_address` which derives the address via:
```
address = keccak256(rlp([sender_address,sender_nonce]))[12:]
```
-
-
-
> create opcode uses deterministic evm contract address

- src/kakarot/instructions/environmental_information.cairo
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/unit/src/kakarot/instructions/test_environmental_information.cairo
Time spent on this PR: 3 HRS
Resolves #446 
- `RETURNDATACOPY` in PlainOpcode test doesn't fail
- Updated `test_should_return_owner_as_origin_and_caller_as_sender` test to check returned values
- `test_should_return_owner_as_origin_and_caller_as_sender` is still skipped as it requires #445 to be merged
> fix: RETURNDATACOPY fails in PlainOpcode test #446

- src/kakarot/instructions/memory_operations.cairo
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
Time spent on this PR: 1.1 days
The exec_jumpi opcode uses the low field of the popped skipped condition to do the check if it is 'anything other than zero'
https://github.com/sayajin-labs/kakarot/blob/b5423b73dc8c32ecbd6701c5a566dc3ae3fc495b/src/kakarot/instructions/memory_operations.cairo#L224
This causes the bug because for the case of the input address of 2^128, it creates a uint with a low of zero and a high of 1. The highest range of representation the low field can do is 2^128-1.
Resolves #439 
Now we do a uint256_le check to have consistent results with the evm.
I made a branch that preserves the minimized changes I added to enable debugging only when the execution_at_address entry point. I generated a log file for the passing …
> fix: do uint256 comparison for condition validity in jumpi opcode

- poetry.lock
- pyproject.toml
- scripts/utils.py
Time spent on this PR: 0.25
`fund_account` use default account ETH to fund given address
In devnet, the `/mint` route is used instead to create ETH out of nowhere
> Use /mint route to fund account in devnet

- .github/workflows/kakarot_devnet.yml
Image built in CI is not pushed to ghcr.io
Tag is fixed and image is pushed to ghcr.io/sayajin-labs/kakarot/devnet
> Add ghcr.io and image name 'devnet' to tag

- pyproject.toml
- src/kakarot/execution_context.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/precompiles/precompiles.cairo
- tests/integration/helpers/wrap_kakarot.py
- tests/integration/solidity_contracts/PlainOpcodes/conftest.py
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/unit/helpers/helpers.cairo
- tests/unit/src/kakarot/accounts/eoa/test_library.py
- tests/unit/src/kakarot/instructions/test_environmental_information.cairo
- tests/unit/src/kakarot/precompiles/test_modexp.py
Revert tests were unable to assert that a given event emitted from a subcontext was not emitted.
The kakarot wrapper now has a `query_logs` method that, when called with 
- no args -> returns the raw logs of transaction.
- contract key -> returns all the events in logs that match the event abi of the contract
-  contract key  x event name -> returns the events that match the particular event name
> feature: add `query_logs` method to kkrt wrapper

- Makefile
- docker/devnet/Dockerfile
The JSON RPC spec does not allow for address missing the leading 0 in hex string
Devnet is started with the `--disable-rpc-request-validation` flag to skip this validation?
See corresponding discussion in https://github.com/Shard-Labs/starknet-devnet/issues/401
> Disable RPC json validation in devnet

- .env_example
- docker/devnet/Dockerfile
- scripts/utils.py
The devnet uses the python VM, which is less performant and unexpectedly crashes when deploying an ERC20.
Use the rust VM instead. As a matter of fact, the ERC20 deployment failing after ~1m20s is now passing in ~25s on my laptop
Updated the .env variables to simplify the get_account method
> Use rust VM for devnet

- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/system_operations.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.cairo
- tests/unit/src/kakarot/instructions/test_environmental_information.py
- tests/unit/src/kakarot/instructions/test_system_operations.cairo
Time spent on this PR: .1
Gasprice was returning a nonconstant value that was dependent on execution.
Gasprice returns the amount of ether that the sender is willing to pay per unit of gas to execute the transaction.
I believe gasPrice is relayed from the rpc to the execution system, but currently only `gas_limit` is parameterized at the entry point of `execute_at_address`, so pragmaticly this opcode is always returning zero.
> gasprice should return txn constant

- scripts/utils/starknet.py
Fix the address to be hex inside the fund_address function when the input is of type int and the network is devnet.
Upon investigating #568 , I found that the following function calls are involved:
- deploy_and_fund_evm_address 
- fund_address
When we investigate fund_address, the following code snippet is where the error comes from:
```python
address = int(address, 16) if isinstance(address, str) else address
amount = amount * 1e18
if NETWORK == "devnet":
response = requests.post(
f"{GATEWAY_CLIENT.net}/mint", json={"address": address, "amount": amount}
)
if response.status_code != 200:
logger.error(f"Cannot mint token to {address}: {response.text}")
logger.info(f"{amount / 1e18} ETH minted to {address}")
```
the address is expected to …
> fix(fund_address): fix address to be hex when network is devnet

- scripts/constants.py
- scripts/deploy_kakarot.py
- scripts/utils/starknet.py
Time spent on this PR: 3 days
The deploy script relying on starknet-py doesn't work on katana (and on madara).
Works on katana (and most probably on all the RPC using starknet-rs).
The blockers were:
- the `offset` type of the `entry_points_by_type` being output as `int` by `starknet-compile-deprecated` while expected as `hex` by the JSON RPC spec
- `starknet-py` mutating the `program` object while computing the class hash (adding `debug_info=None` and clearing `attributes`
- `starknet-rs` not able to handle declare as an object and not a list (should be fixed now however)
> Write custom declare to fix RPC types mismatch

- Makefile
remove `build-devnet` and `build-mac` make commands as they are not used anywhere in the codebase.
`build-devnet` and `build-mac` make commands exist in Makefile.
Resolves #596 
`build-devnet` and `build-mac` make commands are removed from the Makefile.
> dev: remove `build-devnet` and `build-mac` make commands

- .env.example
- scripts/constants.py
- scripts/deploy_kakarot.py
Time spent on this PR: 0.25
Two unrelated topics:
1. the chain_id enum has some hard-coded values that needs to be maintained
1. the deploy scripts first deploy an OZ account in madara and sharingan. This was done because no standard account was available on these networks
Two unrelated updates:
1. the chain_id is now taken from the network itself so it's always the right one
1. no more initial deployment of an account in madara and sharingan because an OZ account has been added in the genesis state. The util is not removed though because it is useful to have it ready in case we need to create on the fly several accounts.
> Minor updates to deploy scripts after latest sharingan release

- .env.example
- scripts/utils/kakarot.py
- scripts/utils/starknet.py
The invoke/deploy/declare functions always log with a ✅ even though the tx didn't succeed.
This "regression" has been introduced when the `wait_for_transaction` has been updated to handle
"Transaction not found" by introducing a timeout.
Currently, at the end of the timeout, even if the tx is not `ACCEPTED_ON_L2`, the logs show a misleading ✅.
Show ❌ when status is not ACCEPTED_ON_L2
Usually, clients raise when a tx is not eventually `ACCEPTED_ON_L2`, while we currently don't.
I added the emoji to make the logging more accurate without changing the behavior. Actually I don't
know if we should raise, the problem coming from the fact that REJECTED tx are not found neither in
RPCs. Say it differently, …
> Improve logging of starknet utils

- scripts/constants.py
- scripts/utils/kakarot.py
- scripts/utils/starknet.py
We migrated to use only a RPC starknet provider. However, in the latest Starknet upgrade, the RPC doesn't return
the same data as the Gateway (espc. transaction status, nonce).
After spending a bit of time to hack the RPC data, I decided to just put the Gateway client for these networks where it is available.
Use Gateway for mainnet/testnet/testnet2
> Use Gateway provider in testnet

- scripts/utils/starknet.py
The `compile_contract` util should add the debug info when the target network is `devnet` but it currently doesn't as the whole `NETWORK` dict is
used instead of `NETWORK["name"]` (missed change during a previous refacto).
`"debug_info"` added in output program
We may want ot activate this flags for other "devnet-like" (katana, madara) but I wasn't sure about the naming, and went just for the fix.
We could though rename `devnet` in `starknet-devnet`, and create a `is_devnet` attribute in the network config, to eventually filter on this and not on the name.
> Fix compile_contract never add debug_info

- docker/katana/scripts/download_katana.sh
The link to the dojo assets that we are using got broken, so updating to the latest link so that the Katana image build works.
Also, will look into a better of way of permanently storing these assets.
The Katana image should be breaking because of links not working.
Resolves #615 
- The Katana image should be building.
> fix: fix broken asset links for katna image

- scripts/constants.py
- scripts/utils/kakarot.py
`chain_id` is fetch from the given RPC endpoint. Even though we now use the Gateway for mainnet/testnet/testnet2,
we then still need an RPC endpoint just for this.
`fetch_deployments` is called when network is not `devnet` and raises if no deployment is found. This is not
really necessary and was done so when we used only devnet/testnet/mainnet.
`chain_id` is prefilled for testnet/testnet2/mainnet
`try/catch` around `fetch_deployments`
> Minor devX improvements

- scripts/constants.py
- scripts/utils/starknet.py
Time spent on this PR: 0.15
When trying to deploy to testnet using the gateway and no RPC, the script raises.
Pass, see locally tested output:
```
STARKNET_NETWORK=testnet python scripts/deploy_kakarot.py
WARNING:scripts.constants:⚠️  TESTNET_ACCOUNT_ADDRESS not set, defaulting to ACCOUNT_ADDRESS
WARNING:scripts.constants:⚠️  TESTNET_PRIVATE_KEY not set, defaulting to PRIVATE_KEY
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI' with Gateway testnet
INFO:__main__:ℹ️  Using account 0x2e2226d64eb35c27f72beb528221884046b2ee1ef96b659aeb1351c4daad971 as deployer
INFO:scripts.utils.starknet:ℹ️  Declaring kakarot
INFO:scripts.utils.starknet:✅ kakarot class hash: 0x71aabb944873364ad1cddf2ea849bc6796c1d7022db71ce942ddb3c09a8987f …
```
> Fix gateway only deployment

- scripts/constants.py
Madara is qualified as `devnet: True` in the networks config.
However, it seems that madara declare doesn't accept `debug_info` that the compile
script leaves when targeting a `devnet` network.
madara is not a devnet, and:
```bash
STARKNET_NETWORK=madara make deploy
```
works again.
> Do not qualify madara as devnet

- .github/workflows/deployments.yml
- docker/deployer/Dockerfile
- scripts/constants.py
No Docker image for just deploying the kakarot contracts to a given network.
Added a deployer image such that
```bash
docker run -e SHARINGAN_ACCOUNT_ADDRESS= -e SHARINGAN_PRIVATE_KEY= -e SHARINGAN_RPC_URL= deployer
```
will deploy Kakarot to the given `SHARINGAN_RPC_URL` network, using as deployer `SHARINGAN_ACCOUNT_ADDRESS` with private key `SHARINGAN_PRIVATE_KEY`.
> Add a docker image to act as a Kakarot deployer

- src/kakarot/execution_context.cairo
- src/kakarot/instructions.cairo
- tests/integration/solidity_contracts/PlainOpcodes/Safe.sol
- tests/integration/solidity_contracts/PlainOpcodes/conftest.py
- tests/integration/solidity_contracts/PlainOpcodes/test_safe.py
Hacker house :)
Breaks when EOA calls `withdraw()` because it thinks it's the end of a CREATE opcode. 
The `func run()` checks if the starknet contract address has 0 bytecode length and is not an EAO, then it follows the CREATE opcode if/else branch. Otherwise, it finalizes the call.
> Fix finalize_context breaking when caller is EOA

- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/instructions/test_system_operations.py
Time spent on this PR: 0.01
#649 changes the ability for testing to mock a nonce as a precondition for an assert.
Resolves #654 
- We separate the further testing of deterministic addresses by a range of nonces to be done directly on `CreateHelper.get_create_address`, instead of the previous way which depended on the ability to establish a mock nonce value before running `SystemOperations.exec_create`
-
-
Currently there is a redundancy of only testing the zero case of nonce for the `test_create`, we can factor out all nonce/address assertions in `test_create` and have them done in a separate test, `test_create_has_deterministic_address`
> test_create_has_determistic_address tests address w/o state

- src/kakarot/accounts/contract/contract_account.cairo
- src/kakarot/accounts/eoa/externally_owned_account.cairo
- src/kakarot/accounts/eoa/library.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/library.cairo
- tests/integration/accounts/test_contract_account.py
- tests/integration/conftest.py
- tests/integration/solidity_contracts/PlainOpcodes/conftest.py
- tests/integration/solidity_contracts/PlainOpcodes/test_counter.py
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/integration/solidity_contracts/Solmate/test_erc20.py
- tests/integration/solidity_contracts/Solmate/test_erc721.py
- tests/integration/solidity_contracts/UniswapV2/conftest.py
- tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_erc20.py
- tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
- tests/integration/solidity_contracts/conftest.py
- tests/src/kakarot/accounts/eoa/mock_externally_owned_account.cairo
- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/instructions/test_system_operations.py
This pr removes nonce management and uses starknet nonce wherever nonce is required.
We currently manage nonce ourselves which causes multiple issues, migrating to starknet nonce is a better solution and the PR implements the required changes for that.
Resolves #648 
- nonce management has been removed
- we now use starknet nonce wherever required
- The rpc is already [using starknet nonce](https://github.com/kkrt-labs/kakarot-rpc/blob/d6e3676de6fc9e804dc751aa3493810c95957bba/crates/core/src/client/mod.rs#L338), which means that the current transactions by tools like metamask are already being signed with starknet nonce and not our own nonce when RPC is being used.
> feat: remove nonce management, use starknet  nonce

- scripts/utils/kakarot.py
Time spent on this PR: 0.5 days
Deploy on testnet fails.
Resolves #666 
- Add gateway_client conditions
Fix tested in devnet and testnet:
DEVNET:
(py39) kali:~/kakarot$ make deploy
poetry lock --check
poetry.lock is consistent with pyproject.toml.
make clean
make[1]: Entering directory '/home/kali/kakarot'
rm -rf build
mkdir build
make[1]: Leaving directory '/home/kali/kakarot'
poetry run python ./scripts/compile_kakarot.py
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI' with RPC http://127.0.0.1:5050/rpc
INFO:__main__:ℹ️  Compiling contracts for network starknet-devnet
INFO:__main__:⏳ Compiling {'contract_name': 'kakarot', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 45.90s
INFO:__main__:⏳ Compiling …
> Fix testnet deploy adding gateway_client calls in kakarot.py

- src/kakarot/execution_context.cairo
- tests/integration/test_kakarot.py
- tests/utils/contracts.py
Currently we emit the evm address linked to the log as the last key of the Starknet event. This causes issues when indexing events on Starknet, as the evm address can be located as different places the in key array depending on the amount of topics included in the log.
Evm address is emitted as last key of the Starknet event, after all topics.
Resolves #NA
- Evm address emitted as first key of the Starknet event, before any topics
> fix: update events emissions logic

- scripts/constants.py
- scripts/deploy_kakarot.py
- scripts/utils/starknet.py
- src/kakarot/execution_context.cairo
This PR updates the deploy script to deploy a pre-funded account to be used at the RPC for deploying EOAs for only Madara and Katana. 
It also updates the compilation script to compile [OpenzeppelinAccount.cairo](https://github.com/kkrt-labs/kakarot/blob/main/src/utils/OpenzeppelinAccount.cairo) the build of which will be required for a future feature PR to the RPC for deploying accounts if they don't exist. 
- We would have to manually fund these accounts when we run Madara { you can read the linked issue to understand why we we are not using the default accounts provided by Madara }
- [OpenzeppelinAccount.cairo](https://github.com/kkrt-labs/kakarot/blob/main/src/utils/OpenzeppelinAccount.cairo) is not part of compilation
Resolves #673 …
> feat: update deploy script to fund and deploy deployer accounts, Make OpenzeppelingAccount.cairo part of compilation script

- pyproject.toml
- src/kakarot/library.cairo
- tests/integration/conftest.py
- tests/integration/solidity_contracts/EFTests/test_sha3.py
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
- tests/integration/solidity_contracts/conftest.py
No fixture available for deploying raw bytecode (not from compilation artifacts) or setting a bytecode (without running it as in deploy).
Added fixtures:
- `deploy_eoa(private_key)` to deploy an EOA
- `deploy_bytecode(bytecode)` to deploy a given raw bytecode
- `create_account_with_bytecode(bytecode)` to create a CA with the given bytecode
Also added a first EF test (sha3_d0g0v0_Shanghai), currently failing due to the `return_data` shorted than the `retSize`.
> Add fixtures for debugging EF tests, and sha3_d0g0v0_Shanghai test

- README.md
Newton project has been discontinued. Let's remove it from the readme.
resolves #621
> docs: remove Newton mentions from the readme

- src/kakarot/instructions.cairo
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
Ensure that the finalization logic accounts for cases where return_data_len is zero, to correctly branch into 'create' or 'call' operations.
Resolves #696 
per this suggestion: https://github.com/kkrt-labs/kakarot/issues/696#issuecomment-1693405166
we add a check if the return data length is zero to decide whether the execution context should be handed as create/call.
-
-
-
> Add condition for zero return_data_len in finalization if-statement

- scripts/utils/kakarot.py
- src/kakarot/accounts/library.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- tests/src/kakarot/accounts/eoa/mock_kakarot.cairo
The Kakarot contract cannot know whether a starknet address is deployed or not.
Resolves #719 #474
A mapping evm_address -> starknet_address has been added:
- returns the starknet_address when it's deployed
- returns 0 otherwise
I didn't replace all the `compute_starknet_address`, and did actually the minimal changes,
since it is still possible in some case (e.g. transfer) to send ETH to a non deployed account.
However, now that we have introduced a mapping, we could move away from this deterministic mapping
to allow any starknet contract to claim ownership of an EVM address.
This is let to further dev, probably in cairo1.
> Add evm to starknet address mapping

- src/kakarot/library.cairo
- tests/integration/solidity_contracts/PlainOpcodes/RevertTestCases.sol
- tests/integration/solidity_contracts/PlainOpcodes/Safe.sol
- tests/integration/solidity_contracts/PlainOpcodes/test_counter.py
- tests/integration/solidity_contracts/PlainOpcodes/test_safe.py
- tests/integration/solidity_contracts/conftest.py
- As of now we cannot transfer `value` when making a transaction `to`: "", i.e during an account creation.
Resolves #682 
- The value transfer during contract deployment is allowed.
> fix: allow transfer of `value` during contract creation

- pyproject.toml
- tests/integration/solidity_contracts/EFTests/test_sload.py
Resolves https://github.com/kkrt-labs/kakarot/issues/732
- Add failing test for SLOAD: sloadGasCost_d0g0v0_Shanghai
- Marking it to fail due to `GAS` opcode being stored
> feat: add failing `sloadGasCost_d0g0v0_Shanghai` test

- src/kakarot/accounts/contract/library.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/library.cairo
- tests/integration/solidity_contracts/PlainOpcodes/test_plain_opcodes.py
Created contract account nonce is not set to 1 after creation
Resolves #715 
- Move setting of nonce to initialize
- Created contract account nonce is set to 1 after creation
> dev: set contract account nonce to 1 after CREATE/CREATE2

- scripts/utils/starknet.py
- tests/end_to_end/conftest.py
- tests/end_to_end/test_kakarot.py
Neither Starknet.py wait_for_acceptance not our `wait_for_transaction` util accept
RPC v4 response, with the `status` field replaced by `execution_status` and `finality_status`.
Also search for `finality_status` key in the receipt.
> Make wait_for_transaction handle v4 RPC

- tests/integration/ef_tests/test_ef_blockchain_tests.py
- tests/integration/ef_tests/utils.py
https://github.com/kkrt-labs/kakarot/blob/5d0390e3f7fd55e08f7129c11373ada2aec5b955/tests/integration/ef_tests/test_ef_blockchain_tests.py#L44
Storage key argument and value are in the wrong order.
https://github.com/kkrt-labs/kakarot/blob/5d0390e3f7fd55e08f7129c11373ada2aec5b955/tests/integration/ef_tests/test_ef_blockchain_tests.py#L102
`is_account_eoa` is passed the wrong dict object in `assert_post_state`
- Corrected order of `evm_to_starknet_address
- `assert_post_state` determines `is_account_eoa` correctly
> fix `evm_to_starknet_address` storage entry in `setup_test_state` and `is_account_eoa` predicate in `assert_post_state`

- .trunk/trunk.yaml
- scripts/compile_kakarot.py
- scripts/utils/starknet.py
- src/kakarot/execution_context.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/stop_and_arithmetic_operations.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/model.cairo
- src/kakarot/precompiles/precompiles.cairo
- tests/src/kakarot/instructions/test_environmental_information.cairo
- tests/src/kakarot/instructions/test_stop_and_arithmetic_operations.cairo
- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/precompiles/test_precompiles.cairo
- tests/utils/helpers.cairo
Time spent on this PR: 0.4
Fails to finalize a calling context when `ret_size` is greater than `return_data_len`.
Resolves #718 
Use `Helpers.slice` to make sure that the stored `return_data` is big enough.
Note: we previously stored the `ret_offset` in the `sub_context.return_data[0]`. I have put both `ret_offset` and `ret_size` in the calling_context return data, as:
- this is more logical: they belong to the calling context and not the sub context
- it is safe because return_data is only written in RETURN, which stops the context, so no data could have been put before a call
- actually I've seen that geth and the execution spec reads RETURNDATASIZE and RETURNDATACOPY directly from the execution context and don't keep a ref to the …
> Fix OutOfBounds for return_data

- scripts/utils/kakarot.py
- solidity_contracts/src/PlainOpcodes/Counter.sol
- tests/end_to_end/PlainOpcodes/test_counter.py
Time spent on this PR: 0.05
Kakarot doesn't revert when doing `0 - 1` for `uint256`.
There was already an issue, I just added a test.
Still not passing
> Add test case for issue 683 & 684

- src/kakarot/account.cairo
`Account.set_code` assert that the account has no code.
This cause `evm.finalize` to break, even though the tx is reverted.
No assertion, this is not the role of the `Account` to make sure that it's allowed to actually write code.
> Remove wrong assert in Account.set_code

- scripts/utils/kakarot.py
- solidity_contracts/src/PlainOpcodes/PlainOpcodes.sol
- solidity_contracts/tests/PlainOpcodes.t.sol
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/memory.cairo
- tests/end_to_end/PlainOpcodes/test_counter.py
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/PlainOpcodes/test_safe.py
- tests/end_to_end/Solmate/test_erc20.py
- tests/end_to_end/Solmate/test_erc721.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_factory.py
- tests/end_to_end/conftest.py
No simple way to create a contract with a given bytecode in Katana.
Added an util to take the target bytecode and put it as RETURN_DATA of a simple tx.
Assert that the finally stored bytecode is the expected one.
I've also updated slightly the utils due to max_fee errors arising in Katana
when restarting tests without restarting Katana.
> Add deploy_bytecode utils and fix dict_ptr error in memory.finalize

- src/kakarot/instructions/stop_and_arithmetic_operations.cairo
- src/kakarot/model.cairo
All the opcodes share the same pre and post processing (assert stack size, pop, push, increment gas) but the code doing it
is duplicated in each opcode.
Created a `exec_arithmetic_operation` that does the main logic and is used in each opcode.
Note that this is the first step of a refacto of the main jump table (evm.cairo) to jump
opcode families (ArithmeticOperations in this context) and not opcode directly.
This will allow opcodes of the same group (that often share the same logic) to reuse more code
(and hopefully save on steps).
> Use generic function for arithmetic ops

- scripts/ef-tests/debug.py
Time spent on this PR: NA
ef-tests debug script only matches exact test name
Resolves #NA
Will check if given `TEST_NAME` is in name of th ef-test
> fix: update debug script

- src/utils/eth_transaction.cairo
R and S part of the signature are assumed to be 32 bytes.
Resolves [573](https://github.com/kkrt-labs/ef-tests/issues/573)
R and S are correctly decoded by taking the length of the values.
> fix: signature extraction in decode legacy tx

- src/kakarot/instructions/block_information.cairo
In BlockInformations, there is a big if/else to map the opcode number to the given opcode label.
Add a jump table to jump to the correct jump location.
> Use jump table in Block Informations

- src/kakarot/account.cairo
When an account is not registered, it's deployed as a CA in `commit` in any cases.
Resolves #793
A contract is deployed only if it has code or nonce.
> Commit account iif it has code or nonce

- src/kakarot/errors.cairo
- src/kakarot/precompiles/blake2f.cairo
- src/kakarot/precompiles/datacopy.cairo
- src/kakarot/precompiles/ec_recover.cairo
- src/kakarot/precompiles/ecadd.cairo
- src/kakarot/precompiles/ecmul.cairo
- src/kakarot/precompiles/modexp.cairo
- src/kakarot/precompiles/precompiles.cairo
- src/kakarot/precompiles/ripemd160.cairo
- src/kakarot/precompiles/sha256.cairo
- tests/src/kakarot/precompiles/test_blake2f.cairo
- tests/src/kakarot/precompiles/test_blake2f.py
- tests/src/kakarot/precompiles/test_datacopy.cairo
- tests/src/kakarot/precompiles/test_datacopy.py
- tests/src/kakarot/precompiles/test_ec_add.cairo
- tests/src/kakarot/precompiles/test_ec_mul.cairo
- tests/src/kakarot/precompiles/test_ec_recover.cairo
- tests/src/kakarot/precompiles/test_ec_recover.py
- tests/src/kakarot/precompiles/test_modexp.cairo
- tests/src/kakarot/precompiles/test_precompiles.cairo
- tests/src/kakarot/precompiles/test_precompiles.py
- tests/src/kakarot/precompiles/test_ripemd160.cairo
- tests/src/kakarot/precompiles/test_sha256.cairo
Some Cairo VM errors in precompiles
Returns a reverted context as in other errors.
> Stop reverting on precompiles

- scripts/utils/kakarot.py
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/precompiles/precompiles.cairo
Time spent on this PR: 0.15
Some ef tests are crashing the Cairo VM with errors likes `Error message: ERC20 cannot send to address 0`.
The precompile sub_ctx uses the true corresponding starknet address.
Transfer is added in a CALL only if value > 0.
> Use true corresponding starknet address for precompiles

- src/kakarot/account.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/library.cairo
- src/kakarot/state.cairo
When a newly deployed contract calls SELFDESTRUCT, it's never deployed on Starknet and consequently
Kakarot is not allowed to `transferFrom` its contract.
The Cairo VM hence raises in `state.commit`.
In `State.commit`, when executing transfer to a newly deployed selfdestructed contract, uses
the Kakarot contract instead as temporary ETH holders.
Note: I have eventually realized that separating the balance from the rest of the Account "to save on loading bytecode just to send ETH" is indeed a nonsense because there is only two ways to send ETH without requiring the bytecode:
- the initial `value` of a tx, hence the sender is an EOA and loading its bytecode is just loading empty code so cheap
- the recipient of …
> Fix ERC20 error due to newly deployed SELFDESTRUCT contracts

- src/kakarot/instructions/stop_and_math_operations.cairo
- src/utils/uint256.cairo
- tests/src/kakarot/instructions/test_stop_and_math_operations.py
> feat: fast_exp

- src/data_availability/starknet.cairo
- src/kakarot/account.cairo
- src/kakarot/events.cairo
- src/kakarot/evm.cairo
- src/kakarot/instructions/block_information.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/logging_operations.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- src/kakarot/model.cairo
- src/kakarot/state.cairo
- src/kakarot/storages.cairo
- tests/fixtures/EVM.cairo
- tests/src/kakarot/instructions/test_environmental_information.cairo
- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/instructions/test_system_operations.py
- tests/src/kakarot/test_account.cairo
- tests/src/kakarot/test_account.py
- tests/src/kakarot/test_state.cairo
The `model.State` maintains a dict for accounts balances.
This is a mis conception due the the false belief that "we don't want
to fetch an account just to send ETH". But there is no way to send ETH
without making a CALL (apart in SELFDESTRUCT).
The balance belongs to the Account instead (as in the ef tests json description for example).
Note: this is a preliminary work to run Kakarot in standalone (no syscall, ie. no Starknet) mode.
> Put balance in Account instead of State

- scripts/utils/kakarot.py
- solidity_contracts/tests/PlainOpcodes.t.sol
- src/data_availability/starknet.cairo
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/conftest.py
Resolves #821
Overwrite bytecode if stored bytecode len doesn't match account.code_len
> Fix bytecode is not written when starknet contract already exists

- src/kakarot/instructions/system_operations.cairo
- src/kakarot/state.cairo
- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/instructions/test_system_operations.py
Time spent on this PR: 0.2 day
Resolves #795 
- add early return for collision in create
- add early return for unsufficient balance in create (value > 0)
> fix: fix early return for create

- solidity_contracts/src/PlainOpcodes/Counter.sol
- tests/end_to_end/PlainOpcodes/test_counter.py
A test is marked as failed while it has the expected behavior
No test for safe sub.
Resolves #683
Fixed tests.
Behavior was already correct.
> Fix safe uint256 sub

- src/kakarot/instructions/system_operations.cairo
`ctx` is returned but not halted
Resolves #816
Halted as per the https://github.com/ethereum/execution-specs/blob/3fe6514f2d9d234e760d11af883a47c1263eff51/src/ethereum/shanghai/vm/instructions/system.py#L533
> Halt ctx in SELFDESTRUCT

- src/kakarot/instructions/duplication_operations.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/precompiles/ecadd.cairo
- src/kakarot/precompiles/ecmul.cairo
- src/kakarot/precompiles/modexp.cairo
- src/kakarot/precompiles/ripemd160.cairo
- src/kakarot/precompiles/sha256.cairo
- src/utils/array.cairo
- src/utils/bytes.cairo
- src/utils/rlp.cairo
- src/utils/uint256.cairo
- src/utils/utils.cairo
- tests/src/kakarot/instructions/test_environmental_information.cairo
- tests/src/kakarot/instructions/test_system_operations.cairo
- tests/src/kakarot/precompiles/test_blake2f.cairo
- tests/src/kakarot/precompiles/test_ec_add.cairo
- tests/src/kakarot/precompiles/test_ec_mul.cairo
- tests/src/kakarot/precompiles/test_ec_recover.cairo
- tests/src/utils/test_array.cairo
- tests/src/utils/test_array.py
- tests/src/utils/test_uint256.cairo
- tests/src/utils/test_uint256.py
- tests/src/utils/test_utils.cairo
- tests/utils/helpers.cairo
Time spent on this PR: 2
Some casting utils in `utils.utils.Helpers`, sometimes redundant, sometimes with non consistant naming, sometime very expensive.
Resolves #835
New utils in dedicated files with EVM consistent naming and signature.
> Add casting utils

- .github/workflows/ci.yml
ci: use ef-tests main branch since signature location change has been merged
> ci: use ef-tests main branch

- src/kakarot/errors.cairo
- src/kakarot/evm.cairo
- src/kakarot/gas.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/logging_operations.cairo
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/push_operations.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interpreter.cairo
- tests/src/kakarot/test_execution_context.py
Time spent on this PR: 1
Stack outputs are Uint256 and they are sometimes casted without checks (either keeping only `.low` or `low + high * 2 ** 128`).
Resolves #855
Stack values are handled before using `.low`.
> Fix stack output casting

- blockchain-tests-skip.yml
- solidity_contracts/src/PlainOpcodes/PlainOpcodes.sol
- src/kakarot/instructions/stop_and_math_operations.cairo
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
Resolves #695 Resolves #691 
- Fixed the addmod implementation
-
-
> fix: addmod impl

- .github/workflows/ci.yml
- blockchain-tests-skip.yml
- src/kakarot/account.cairo
- src/kakarot/evm.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/model.cairo
- src/kakarot/precompiles/precompiles.cairo
- src/utils/array.cairo
- src/utils/utils.cairo
- tests/src/kakarot/precompiles/test_precompiles.cairo
- tests/src/kakarot/test_execution_context.py
- tests/src/utils/test_array.cairo
- tests/src/utils/test_array.py
- tests/utils/helpers.cairo
Time spent on this PR: 1d
Resolves #693 
- JUMP and JUMPI can only jump to valid jumpdests
- valid jumpdests are stored in the message struct once the bytecode to execute is known.
-
> feat: valid jumpdests

- .trunk/.gitignore
- .trunk/trunk.yaml
- src/kakarot/state.cairo
- tests/fixtures/starknet.py
- tests/src/kakarot/test_state.cairo
- tests/src/kakarot/test_state.py
The `cairo_run` fixture cannot compile `%lang starknet` files.
Works, see for example [test_state](./tests/src/kakarot/test_state.py)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/883)
> Allow cairo_run to be used with %lang starknet cairo files

- tests/fixtures/starknet.py
- tests/src/kakarot/test_gas.cairo
- tests/src/utils/test_array.cairo
- tests/src/utils/test_bytes.cairo
- tests/src/utils/test_eth_transaction.cairo
- tests/src/utils/test_rlp.cairo
I didn't realize first that calling a test entrypoint is like calling any function in cairo, meaning that one has
- args up to `[fp - 3]`
- return `fp`
- return `pc`
and that it's precisely what's done in the runner initialization. By just updating the order of the segment, the `output` segment is just accessed as the last (and only currently as we yet don't parse input args) argument.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/893)
> Fix segments order in cairo runner

- scripts/utils/starknet.py
- tests/utils/helpers.cairo
The `print_XXX` hints in `tests/utils/helpers.cairo` still use some non implemented hints.
The `print_felt` hint is missing.
Fixed these utils, such that they can be used as is with the ef-test runner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/901)
> Fix print helpers based on new hints

- tests/fixtures/starknet.py
- tests/utils/hints.py
Time spent on this PR: 0.15
When running a cairo program, there is no easy way to locate the corresponding cairo code.
Added a `debug_info` util that can be called directly from a hint with `debug_info(pc)` to
print the corresponding `debug_info` (cairo source code).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/915)
> Add debug_info hint util

- src/kakarot/state.cairo
- tests/src/kakarot/test_state.cairo
- tests/src/kakarot/test_state.py
Resolves #900
- Fixes `is_account_alive` which should return false only if the account has no nonce / code / balance globally
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/954)
> fix: is_account_alive

- .github/workflows/ci.yml
`make setup` does fetch them but may be skipped if no deps changed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/991)
> Fetch ssj artifacts for end to end in ci

- .github/workflows/ci.yml
- scripts/utils/kakarot.py
- src/backend/starknet.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/state.cairo
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/PlainOpcodes/test_safe.py
- tests/end_to_end/Solmate/test_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_factory.py
- Charges the sender for the gas consumed in the transaction and value sent. 
- Fixed state commitment to _always_ commit the State on eth_send_transaction
- For "reverted" txs, we reset the State before charging the gas.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1025)
> feat: charge transaction gas to the sender

- tests/src/kakarot/test_kakarot.cairo
Just adding a missing nonce argument in the `eth_call`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1026)
> Fix running profiling for Solmate

- scripts/constants.py
BUGFIX:
Cannot choose the RPC URL for Katana as STARKNET_NETWORK
Breaks Kakarot-Rpc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1031)
> allow custom rpc url for katana and madara

- pyproject.toml
- src/kakarot/constants.cairo
- src/kakarot/gas.cairo
- src/kakarot/instructions/block_information.cairo
- src/kakarot/interpreter.cairo
- tests/end_to_end/bytecodes.py
- tests/src/kakarot/instructions/test_block_information.py
- tests/utils/constants.py
- Adds support for the blobhash opcode.
> the blobhash opcode reads index from the top of the stack as big-endian uint256, and replaces it on the stack with tx.blob_versioned_hashes[index] if index < len(tx.blob_versioned_hashes), and otherwise with a zeroed bytes32 value. The opcode has a gas cost of HASH_OPCODE_GAS.
As we don't support blob transactions, we would be in thecase where `index < len(tx.blob_versioned_hashes)` holds at all times. Thus, we simply push 0 to the stack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1036)
> feat: blobhash (0x49)

- src/kakarot/account.cairo
- src/utils/utils.cairo
- tests/fixtures/starknet.py
- add `is_le_unchecked` function
- exit the loop without using `is_le` at each iteration. Only done once at exit. 
Before : 
After : 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1034)
> Optimize get_jumpdests

- src/backend/starknet.cairo
- src/kakarot/accounts/eoa/library.cairo
- tests/src/kakarot/instructions/test_block_information.cairo
- tests/src/kakarot/instructions/test_block_information.py
- tests/utils/constants.py
- Take chain_id mod 64, as EVM tools don't accept chain_id with values > 64 bits. For example, "SN_SEPOLIA" takes 10 bytes, thus doesn't fit in 64 bits, and cannot be used as a valid CHAIN_ID in wallets. Both the wallets and Kakarot will take CHAIN_ID modulo 64
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1048)
> feat: take chain_id mod 64

- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/utils/bytes.cairo
- src/utils/eth_transaction.cairo
- tests/src/kakarot/instructions/test_environmental_information.py
- tests/src/utils/test_bytes.cairo
- tests/src/utils/test_bytes.py
Time spent on this PR: 0.6d
Resolves #966 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1053)
> feat: use keccak builtin

- src/backend/starknet.cairo
- src/kakarot/instructions/block_information.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/model.cairo
- src/utils/utils.cairo
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/Solmate/test_erc20.py
- tests/end_to_end/conftest.py
Resolves #966
- Removed block_hashes array filled with zeroes from environment
- Get block_hashes from block_hash syscall
-
Note: couldn't test properly yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1062)
> feat: use blockhash syscall

- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/interfaces/interfaces.cairo
- tests/src/kakarot/accounts/test_contract_account.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- tests/utils/syscall_handler.py
Resolves #1045 Resolves #1044
- Added a versioning mechanism to accounts
- 
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1058)
> feat: account versioning

- kakarot_scripts/constants.py
- src/kakarot/accounts/library.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/stop_and_math_operations.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/state.cairo
- src/utils/modexp/modexp_utils.cairo
- src/utils/uint256.cairo
- tests/src/utils/test_uint256.cairo
- tests/src/utils/test_uint256.py
- tests/utils/helpers.cairo
From @feltroidprime work, just added test
Using whitelisted hints:
uint256_add : 22 steps -> 10 steps
uint256_sub : ~60 steps -> 13 steps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1070)
> Optimize uint256_add and uint256_sub

- src/kakarot/interpreter.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- tests/fixtures/EVM.cairo
Resolves #1067
- Adds an eth_estimate_gas entrypoint that returns the required gas for the transaction to run successfully. This is different from gas_used, s.t. `required gas >= gas used`, as the EVM can reimburse gas after its execution.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1074)
> feat: estimate_gas

- src/backend/starknet.cairo
- src/kakarot/account.cairo
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/accounts/uninitialized_account.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- tests/end_to_end/conftest.py
- tests/end_to_end/test_kakarot.py
- tests/src/kakarot/accounts/test_contract_account.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- tests/src/kakarot/test_kakarot.cairo
- tests/src/kakarot/test_kakarot.py
Resolves #1064 Resolves #1046
- Deploys accounts from zero to allow anyone to deploy an account for Kakarot.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1065)
> feat: deploy account from zero

- src/kakarot/accounts/library.cairo
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1085)
> take chain_id modulo u32 in account as well

- src/kakarot/interpreter.cairo
- There were a couple of extra checks already performed in Account.execute() replicated in interpreter.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1084)
> dev: remove extra checks in interpreter

- src/kakarot/accounts/library.cairo
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1090)
> fix: nonce set in __execute__ to use protocol nonce

- kakarot_scripts/constants.py
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/precompiles/ec_recover.cairo
- src/utils/eth_transaction.cairo
- tests/end_to_end/conftest.py
- tests/end_to_end/test_account.py
- tests/fixtures/account_contract_fixture.cairo
- tests/src/kakarot/accounts/test_contract_account.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- tests/src/kakarot/instructions/test_environmental_information.py
- tests/src/utils/test_eth_transaction.cairo
- tests/src/utils/test_eth_transaction.py
- tests/utils/constants.py
- tests/utils/helpers.py
- tests/utils/syscall_handler.py
Time spent on this PR: 0.7d
Full __Cairo Zero__ validation
Transaction resource usage: Steps: 369606 | Bitwise: 3169 | L1 Gas: 5748 | Pedersen: 165 | Range Checks: 22658  
Using __Cairo1_helpers__'s "keccak" and "verify_eth_signature" in validation
Transaction resource usage: Steps: 326384 | Bitwise: 44 | Keccak: 2 | L1 Gas: 5748 | Pedersen: 165 | Range Checks: 20971 
which is a reduction of 43000 steps per tx :)
Method:
Call `counter.inc()` before and after.
- Use Cairo1Helpers in Account contract for keccak and sig verification
- Implement upgradeability mechanism
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> feat: use Cairo1Helpers in AccountContract

- .env.example
- Makefile
- kakarot_scripts/constants.py
Time spent on this PR: 45 -50 mins 
from .env file, the variable STARKNET_NETWORK is used to both:
- decide on which network to deploy kakarot
- decide on which network to run the integration tests
Resolves #1100 
- make test-end-to-end forces STARKNET_NETWORK to be katana
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1106)
> dev: enforce katana in make test-end-to-end

- .github/workflows/ci.yml
- .github/workflows/deployments.yml
- .github/workflows/release.yml
- Makefile
- docker/deployer/Dockerfile
- kakarot_scripts/utils/kakarot.py
- poetry.lock
- pyproject.toml
- tests/src/kakarot/test_state.py
- bump some deps in CI
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1118)
> ci: update dependencies

- Makefile
- kakarot_scripts/constants.py
- kakarot_scripts/utils/kakarot.py
- pyproject.toml
- solidity_contracts/src/UniswapV2/test/ERC20.sol
- solidity_contracts/src/UniswapV2Router/UniswapV2Router02.sol
- solidity_contracts/src/UniswapV2Router/interfaces/IERC20.sol
- solidity_contracts/src/UniswapV2Router/interfaces/IUniswapV2Router01.sol
- solidity_contracts/src/UniswapV2Router/interfaces/IUniswapV2Router02.sol
- solidity_contracts/src/UniswapV2Router/interfaces/IWETH.sol
- solidity_contracts/src/UniswapV2Router/libraries/SafeMath.sol
- solidity_contracts/src/UniswapV2Router/libraries/TransferHelper.sol
- solidity_contracts/src/UniswapV2Router/libraries/UniswapV2Library.sol
- solidity_contracts/src/WETH/WETH9.sol
- tests/end_to_end/UniswapV2/conftest.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_router.py
- tests/end_to_end/conftest.py
Resolves #1123 
- new tests covering uniswapv2 router
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1124)
> feat: add skeleton for uniswapv2router tests

- src/kakarot/accounts/library.cairo
- src/utils/eth_transaction.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- tests/src/utils/test_eth_transaction.py
- tests/utils/constants.py
- tests/utils/helpers.py
Time spent on this PR:  0.5d
Resolves #1144 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1145)
> feat: pre eip155 tx

- .github/workflows/ci.yml
- kakarot_scripts/deploy_kakarot.py
- kakarot_scripts/utils/find_selector.py
- src/backend/starknet.cairo
- src/kakarot/account.cairo
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/evm.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/model.cairo
- src/utils/utils.cairo
- tests/end_to_end/bytecodes.py
- tests/end_to_end/test_kakarot.py
- tests/fixtures/EVM.cairo
- tests/src/backend/test_starknet.cairo
- tests/src/backend/test_starknet.py
- tests/src/kakarot/accounts/test_contract_account.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- tests/src/kakarot/test_account.cairo
- tests/src/kakarot/test_account.py
- tests/src/kakarot/test_evm.cairo
- tests/src/kakarot/test_evm.py
- tests/src/utils/test_utils.cairo
- tests/src/utils/test_utils.py
- tests/utils/helpers.cairo
- tests/utils/hints.py
Benchmark: using `test_should_add_liquidity` (a test that switches back-and-fourth between multiple contracts multiple times and thus should benefit from the caching mechanism)
**Before**
```
TRACE executor: Transaction resource usage. usage="Steps: 8093994 | Bitwise: 1420 | Keccak: 115 | L1 Gas: 364303 | Pedersen: 621 | Range Checks: 391939"
```
**After**
```
Transaction resource usage. usage="Steps: 6344085 | Bitwise: 1420 | Keccak: 115 | L1 Gas: 653027 | Pedersen: 1503 | Range Checks: 308089"
```
=> 1.7M steps saved
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakaro …
> feat: store jumpdests

- src/kakarot/accounts/library.cairo
- tests/src/kakarot/accounts/test_contract_account.py
- Adds a fallback so that if a jumpdest index read is 0 and the jumpdests have not been initialized, initialize them and re-query the index
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1148)
> feat: uninitialized jumpdests fallback

- .github/workflows/ci.yml
- kakarot_scripts/utils/kakarot.py
- src/kakarot/accounts/library.cairo
The signature length of the EOA is limited to 5 (r_low, r_high, s_low, s_high, v). 
Resolves #NA
In order to allow for a retry mechanism to the Starkware appchain, a retry field is added to the signature, extending its length to 6. 
This extra field gives the RPC control over the Starknet transaction hash, allowing the RPC to modify the Starknet hash and bypass the `DuplicateTx` error from the Starkware appchain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1162)
> feat: kakarot signature length

- .env.example
- kakarot_scripts/constants.py
- kakarot_scripts/utils/kakarot.py
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/Solmate/test_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_factory.py
- tests/end_to_end/conftest.py
- tests/src/kakarot/test_kakarot.py
- tests/utils/coverage.py
- tests/utils/errors.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1164)
> Use web3 with Kakarot RPC in end-to-end tests when available

- src/kakarot/instructions/stop_and_math_operations.cairo
- tests/src/kakarot/instructions/test_stop_and_math_operations.py
- tests/src/kakarot/test_kakarot.cairo
- Fixes a bug on `addmod` where if (a+b) overflowed, the carry was not handled
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1170)
> fix: addmod

- src/kakarot/account.cairo
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- tests/src/kakarot/accounts/test_contract_account.cairo
- tests/src/kakarot/accounts/test_contract_account.py
Time spent on this PR: 0.7 days
Resolves #<Issue number> #1094 
all call restriction checks (only owner etc.) in contracts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1179)
> Call restriction checks in contracts

- src/kakarot/kakarot.cairo
- tests/end_to_end/test_kakarot.py
Ownership of the Kakarot contract can't be transfered.
Resolves #1192 
- Add transfer of ownership of the contract.
- Add tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1193)
> feat: add transfer_ownership

- .github/workflows/update-rpc.yml
Note: I've had to create a Personal Access Token with write access to the RPC repo for this to work
See resulting PR in RPC https://github.com/kkrt-labs/kakarot-rpc/pull/1181 (got modifying the `on` condition to trigger the workflow, see also https://github.com/kkrt-labs/kakarot/actions/runs/9481929981/job/26125717974
With the release condition activated, see https://github.com/ClementWalter/kakarot/actions/runs/9483859582/job/26131981795
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1200)
> Add workflow to PR kakarot RPC on release

- src/kakarot/accounts/library.cairo
- tests/fixtures/starknet.py
- tests/src/kakarot/accounts/test_contract_account.py
- tests/src/kakarot/test_kakarot.py
- tests/src/utils/test_eth_transaction.py
- tests/utils/errors.py
- tests/utils/helpers.py
Resolves #1068
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1222)
> dev: catch cairo errors

- Makefile
- src/kakarot/evm.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/model.cairo
- tests/src/kakarot/test_evm.cairo
- tests/utils/helpers.cairo
code_address is of type felt
Resolves #1176 
code_address is of type model.Address*
Example for unit test `test_erc20_transfer`
110391 vs 106371
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1225)
> dev: code address type model address

- solidity_contracts/src/L1L2Messaging/L1KakarotMessaging.sol
- solidity_contracts/src/L1L2Messaging/MessageAppL1.sol
`consumeMessageFromL2` in `L1KakarotMessaging` was not used and commented.
There is a storage collision when calling `L1KakarotMessaging` in delegatecall as `_starknetMessaging` and `_kakarotAddress` are stored in slot 0 and 1.
Resolves #1228
- In `L1KakarotMessaging` contract 
- `_starknetMessaging` and `_kakarotAddress` are passed as immutable
This contract should not have storage if possible to avoid storage collision. If necessary implement [ERC7201](https://eips.ethereum.org/EIPS/eip-7201) or other solution. 
- adds a `self` immutable to add a check in `consumeMessageFromL2` to ensure it is called in `delegatecall` 
- forge fmt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> fix: use immutable in L1KakarotMessaging

- .github/workflows/trunk-check.yaml
- .trunk/trunk.yaml
- foundry.toml
- solidity_contracts/src/CairoPrecompiles/CairoCounterCaller.sol
- solidity_contracts/src/CairoPrecompiles/CairoLib.sol
- solidity_contracts/src/CairoPrecompiles/PragmaCaller.sol
- solidity_contracts/src/L1L2Messaging/MessageAppL2.sol
- solidity_contracts/src/RIP7212/RIP7212Invoker.sol
Time spent on this PR: 0.5h
Resolves #1244
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1247)
> chore: add solidity formatter

- solidity_contracts/src/CairoPrecompiles/CairoCounterCaller.sol
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/errors.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/library.cairo
- src/kakarot/precompiles/kakarot_precompiles.cairo
- src/kakarot/precompiles/precompiles.cairo
- tests/end_to_end/CairoPrecompiles/test_cairo_precompiles.py
- tests/end_to_end/L1L2Messaging/test_messaging.py
- tests/fixtures/Counter.cairo
- tests/src/kakarot/accounts/test_account_contract.cairo
- tests/src/kakarot/accounts/test_account_contract.py
- tests/src/kakarot/precompiles/test_precompiles.cairo
- tests/src/kakarot/precompiles/test_precompiles.py
- tests/utils/syscall_handler.py
0.3d
- Adds a `execute_starknet_call` entrypoint to the account contract class. This entrypoint is invoked by Kakarot and allows calling _any_ other starknet contract deployed on the Starknet Chain
- <!> This could be a re-entrancy attack vector into kakarot. While direct EOA->KKT->EOA->KKT calls have been disabled,  EOA -> KKT -> EOA -> CairoContract -> Kakarot could still happen 🤔 Possible mitigation: ensure callers of non-protected KKT entrypoints like `eth_send_transaction` are either
1) 0 (starknet_call) or 2) a valid Kakarot account (checked against the internal registry)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> feat: add execute_starknet_call entrypoint to account contract

- Makefile
update katana to support rpc spec-version 0.7.0 and latest starknet contracts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1252)
> chore: update katana

- src/kakarot/accounts/account_contract.cairo
- src/kakarot/errors.cairo
- src/kakarot/precompiles/kakarot_precompiles.cairo
- src/kakarot/precompiles/precompiles.cairo
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1254)
> feat: whitelist 'compute_starknet_address' from reentrancy

- solidity_contracts/src/PlainOpcodes/PlainOpcodes.sol
- tests/fixtures/starknet.py
- tests/src/kakarot/test_kakarot.py
Resolves #1249
For max = 10:
For max = 50
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1256)
> dev: loop profiling

- src/kakarot/kakarot.cairo
- src/utils/utils.cairo
- tests/end_to_end/CairoPrecompiles/Pragma/test_pragma_precompile.py
- tests/end_to_end/CairoPrecompiles/test_cairo_precompiles.py
- tests/end_to_end/test_kakarot.py
It is possible to send transactions on `eth_call` and `eth_estimate_gas` kakarot entrypoints
Resolves #1257
Transactions (invoke) will fail on those entrypoints
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1281)
> feat: block transactions on view entrypoints

- src/kakarot/instructions/environmental_information.cairo
- tests/src/kakarot/instructions/test_environmental_information.cairo
- tests/src/kakarot/instructions/test_environmental_information.py
- tests/utils/helpers.cairo
When offset is too high(> 2 ** 128), 0 is not copied to memory.
Resolves #1258 
When offset is too high(> 2 ** 128), 0 is copied in memory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1286)
> bug: fix early return exec copy

- src/kakarot/accounts/library.cairo
- tests/conftest.py
- tests/fixtures/starknet.py
- tests/src/kakarot/accounts/test_account_contract.py
- tests/utils/hints.py
Do not assert the value is 0 at the end of load_bytecode leading to prover being able to 
Resolves #1279, resolves #1293
assert value is 0 at the end of load_bytecode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1290)
> fix: assert value is 0 at the end of load_bytecode

- src/utils/utils.cairo
- tests/src/utils/test_utils.py
Missing contraints in load_packed_bytes
Resolves #1283
load_packed_bytes is not underconstrained
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1299)
> fix: load_packed_bytes is underconstrained

- src/utils/utils.cairo
Resolves #1282
It uses `unsigned_div_rem` to decompose the value
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1301)
> refactor: bytes_used_128 using unsigned_div_rem

- src/kakarot/precompiles/ec_recover.cairo
- src/utils/utils.cairo
- tests/src/utils/test_utils.cairo
- tests/src/utils/test_utils.py
Split word is underconstrained and not tested
Resolves #1278
Split word raise if len > 32 and is tested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1305)
> fix: enforce len < 32 split word

- .gitmodules
- kakarot_scripts/constants.py
- kakarot_scripts/deploy_kakarot.py
- kakarot_scripts/utils/kakarot.py
- kakarot_scripts/utils/l1.py
- solidity_contracts/src/UniswapV2Router/libraries/UniswapV2Library.sol
- solidity_contracts/src/UniswapV3/HexStrings.sol
- solidity_contracts/src/UniswapV3/NFTDescriptor.sol
- solidity_contracts/src/UniswapV3/NFTSVG.sol
- solidity_contracts/src/UniswapV3/UniswapV3NFTManager.sol
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_factory.py
- tests/end_to_end/UniswapV3/test_univ3_rendering.py
- tests/end_to_end/test_kakarot.py
- tests/src/kakarot/test_kakarot.py
- tests/src/utils/test_utils.py
Time spent on this PR: 1d
Adds Mock UniswapV3 contracts that allow querying a dynamically generated on-chain SVG representing a position.
The values are mocked, and due to some issues, the base64 encoding of the image crashes with a stack underflow error (tbd).
However, the encoding of the rest takes ~27M steps
Also: Because `NFTDescriptor` is a library with an `external` function, it must be deployed and called with its address. When referring to this library, the compiler will add a placehold in form `__$HASH_OF_PATH$__` in the compiled bytecode. Thus, I implemented a way of linking a library in the deployments scripts - we can deploy the contract providing a set of required libraries, that are deployed, hashed, and their address replaces the hash in the compiled bytecode.
Please check …
> tests: add univ3 svg generation test

- src/kakarot/instructions/system_operations.cairo
- src/utils/bytes.cairo
- tests/src/utils/test_bytes.cairo
- tests/src/utils/test_bytes.py
Resolves #1300
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1317)
> bug: felt to bytes little underconstrained

- src/kakarot/gas.cairo
- tests/src/kakarot/test_gas.cairo
- tests/src/kakarot/test_gas.py
Resolves #1266
- `memory_expansion_cost_saturated`: offset.high + size.high != 0 can be broken when selecting `(P - 1)/2` and `(P + 1)/2`
- `calculate_gas_extend_memory`: max_offset is a felt possibly > 2**128 so one needs to use `is_le_felt`
- Condition is updated for `memory_expansion_cost_saturated`
- Usage of `is_le_felt` in `calculate_gas_extend_memory`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1322)
> bug: checks memory expansion costs utils

- src/kakarot/accounts/library.cairo
- tests/src/kakarot/accounts/test_account_contract.py
Resolves #1325 
Signature values are checked to be < 2**128
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1331)
> feat: validate signature values

- src/kakarot/precompiles/kakarot_precompiles.cairo
- tests/src/kakarot/precompiles/test_precompiles.py
Resolves #1338
Destination address for cairo_message is checked to be well formatted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1339)
> fix: validate destination address cairo_message

- src/backend/starknet.cairo
- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/kakarot/gas.cairo
- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/memory_operations.cairo
- src/kakarot/instructions/sha3.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/memory.cairo
- src/kakarot/precompiles/blake2f.cairo
- src/kakarot/precompiles/ec_recover.cairo
- src/kakarot/precompiles/ripemd160.cairo
- src/kakarot/precompiles/sha256.cairo
- src/kakarot/stack.cairo
- src/utils/bytes.cairo
- src/utils/dict.cairo
- src/utils/maths.cairo
- src/utils/uint256.cairo
- src/utils/utils.cairo
Resolves #1302
- div_rem and unsigned_div_rem are inlined
From 141777 to 141574
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1342)
> opti: inline unsigned_div_rem and div_rem

- src/utils/eth_transaction.cairo
- src/utils/rlp.cairo
- tests/conftest.py
- tests/fixtures/starknet.py
- tests/src/utils/test_eth_transaction.py
- tests/src/utils/test_rlp.cairo
- tests/src/utils/test_rlp.py
- tests/utils/hints.py
- tests/utils/serde.py
`RLP.decode` doesn't check that the result is consistent with the given len prefix.
In other words, given two encoded items `b1` and `b2`, `RLP.decode(b1 + b2)` will actually decode
`b1` and `b2` while it should raise because `b1 + b2` is not a valid RLP (it's a list with missing prefix).
Resolves #1306
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1307)
> Fix RLP.decode

- src/kakarot/accounts/account_contract.cairo
- src/kakarot/accounts/library.cairo
- src/utils/eth_transaction.cairo
- src/utils/rlp.cairo
- tests/src/kakarot/accounts/test_account_contract.cairo
- tests/src/kakarot/accounts/test_account_contract.py
- tests/src/utils/test_eth_transaction.cairo
- tests/src/utils/test_eth_transaction.py
- tests/src/utils/test_rlp.cairo
- tests/src/utils/test_rlp.py
Segments are not constrained enough, making it possible for a malicious prover to tweak tx data.
Resolves #1313
Added more `assert` to make sure that we don't read data beyond `data_len`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1356)
> Fix underconstrained segments

- .github/workflows/ci.yml
Venv is not cached in CI jobs and takes ~3 minutes to be rebuilt
Path `.venv` set explicitly. Venv is cached.
Removed deprecated `installer.modern-installation false` config
See also : https://github.com/snok/install-poetry/tree/v1/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1361)
> FIx venv not cached in CI

- src/kakarot/library.cairo
- tests/src/kakarot/instructions/test_block_information.py
- tests/src/kakarot/test_kakarot.cairo
- tests/src/kakarot/test_kakarot.py
Resolves #1354
chain_id mod 53
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1359)
> feat: chain_id mod 53

- src/kakarot/accounts/library.cairo
- src/kakarot/eth_rpc.cairo
- src/kakarot/interfaces/interfaces.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/kakarot.cairo
- src/kakarot/library.cairo
- src/kakarot/model.cairo
- src/utils/eth_transaction.cairo
- tests/fixtures/EVM.cairo
- tests/src/kakarot/accounts/test_account_contract.py
- tests/src/kakarot/test_kakarot.cairo
- tests/src/kakarot/test_kakarot.py
- tests/src/utils/test_eth_transaction.py
- tests/utils/serde.py
Resolves #1277
Add `eth_send_raw_transaction` entrypoint
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1357)
> feat: eth_send_raw_transaction

- kakarot_scripts/utils/kakarot.py
- kakarot_scripts/utils/starknet.py
- src/kakarot/evm.cairo
- src/kakarot/instructions/system_operations.cairo
- src/kakarot/interpreter.cairo
- src/kakarot/model.cairo
- tests/end_to_end/CairoPrecompiles/Pragma/test_pragma_precompile.py
- tests/end_to_end/CairoPrecompiles/test_cairo_precompiles.py
- tests/end_to_end/CairoPrecompiles/test_dual_vm_token.py
- tests/utils/errors.py
- tests/utils/helpers.cairo
Resolves #1364
- revert cairo tx when evm tx fails with cairo precompile called
- fix error send back for input validation in cairo precompile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1368)
> fix: revert cairo tx when evm tx with cairo precompile fails

- kakarot_scripts/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1370)
> Minor fixes for sn mainnet

- solidity_contracts/src/CairoPrecompiles/SubContextPrecompile.sol
- src/kakarot/instructions/system_operations.cairo
- tests/end_to_end/CairoPrecompiles/test_cairo_precompiles.py
- tests/end_to_end/conftest.py
Resolves #1377
- Revert cairo tx when evm revert
- cairo_precompile_called ORed when propagated to parent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1378)
> fix: cairo precompile revert for child contexts

- src/utils/utils.cairo
- tests/src/utils/test_utils.py
Resolves #1375
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1384)
> fix: parsing invalid addresses panics

- kakarot_scripts/constants.py
- kakarot_scripts/utils/kakarot.py
- kakarot_scripts/utils/starknet.py
- tests/end_to_end/conftest.py
- tests/fixtures/starknet.py
- tests/src/conftest.py
It's not possible to use pytest-xdist with end to end tests.
Some of the nonce issues have been solved. Katana still drops transaction with no obvious reason/no error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1382)
> dev: prepare parallelization of end to end tests

- src/kakarot/precompiles/kakarot_precompiles.cairo
- tests/src/kakarot/precompiles/test_kakarot_precompiles.cairo
- tests/src/kakarot/precompiles/test_kakarot_precompiles.py
`data_len` is a user input that can be bytes32
Resolves #1373
Couldn't find a real SN limitation for now but `bytes4` is surely more than enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1387)
> Fix cairo_message arbitrary data_len

- src/kakarot/instructions/environmental_information.cairo
- src/kakarot/instructions/memory_operations.cairo
- tests/conftest.py
- tests/src/kakarot/instructions/test_memory_operations.cairo
- tests/src/kakarot/instructions/test_memory_operations.py
Resolves #1372
Overflow checks for memeory operation before charge gas
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1381)
> fix: overflow check memory operations charge gas

- src/utils/eth_transaction.cairo
- tests/src/kakarot/test_kakarot.py
- tests/src/utils/test_eth_transaction.py
The usage of `bytes_to_felt` and `bytes_to_uint256` while decoding the tx is not checking possible overflow of the data.
Resolves #1374
Raise a CairoVM error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1393)
> Fix possible overflow of tx params

- README.md
- docker/deployer/Dockerfile
- Removes the `build-cairo1` step from the release script as it is no longer existing and integrated in the python build instead.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1400)
> remove 'make build-cairo1' from release script

- src/kakarot/precompiles/kakarot_precompiles.cairo
- tests/src/kakarot/precompiles/test_precompiles.py
This precompile is never used but bears a severe security risk as it allows potential attackers to update the state of Kakarot.
Removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1397)
> Remove library_call from precompiles

- README.md
- foundry.toml
- solidity_contracts/src/CairoPrecompiles/DualVmToken.sol
- solidity_contracts/src/L1L2Messaging/L1KakarotMessaging.sol
- solidity_contracts/src/L1L2Messaging/L2KakarotMessaging.sol
- solidity_contracts/src/UniswapV2Router/libraries/UniswapV2Library.sol
Resolves #1419
- fix solidity version for DualVMToken, L1/L2 KakarotMessaging contracts
- enable optimizer 
- make sendMessageToL1 non payable to avoid locking ether
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1425)
> chore: fix solidity version and enable optimizer

- solidity_contracts/src/L1L2Messaging/AddressAliasHelper.sol
- solidity_contracts/src/L1L2Messaging/L1KakarotMessaging.sol
- solidity_contracts/src/L1L2Messaging/MessageAppL1.sol
- solidity_contracts/src/L1L2Messaging/MessageAppL2.sol
- tests/end_to_end/L1L2Messaging/test_messaging.py
Resolves #1229
- adds address aliasing for L1 to L2 message
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1430)
> feat: address aliasing

- src/kakarot/account.cairo
- src/kakarot/constants.cairo
- src/kakarot/state.cairo
- tests/src/kakarot/test_account.cairo
- tests/src/kakarot/test_state.cairo
Resolves #1410
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1431)
> dev: use consts for empty hash

- src/kakarot/eth_rpc.cairo
- src/kakarot/kakarot.cairo
- tests/src/kakarot/test_kakarot.cairo
- tests/src/kakarot/test_kakarot.py
Resolves #1426
- Add a Pausable feature that prevents from using public, state-modifying entrypoint into Kakarot.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1433)
> feat: pausable

- src/kakarot/accounts/account_contract.cairo
- tests/src/kakarot/accounts/test_account_contract.py
`execute_from_outside` purpose is that _validate_ and __execute__  are limited in functionalities. We could not run all EVM checks in validate , and our move to a "real" Starknet chain required a solution to handle the underlying starknet transaction fee for our users.
Thus, we needed to implement a paymaster functionality.
All EVM tx rules validation are now handled in the execute part of a transaction to bypass the limitations of validate , and both these entrypoints have been disabled.
We use a fleet of relayer accounts to sponsor the Starknet cost of the transaction for our users, so that they don't have to worry about Starknet gas
For this, we implemented the execute_from_outside entrypoint as defined in SNIP-9
The outside_execution nonce is not signed, thus anyone can send a …
> dev: remove outside_execution checks & docs

- kakarot_scripts/utils/kakarot.py
- solidity_contracts/src/CairoPrecompiles/DualVmToken.sol
- tests/end_to_end/CairoPrecompiles/test_dual_vm_token.py
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
- tests/end_to_end/Solmate/test_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_erc20.py
- tests/end_to_end/UniswapV2/test_uniswap_v2_factory.py
- tests/utils/errors.py
Resolves #1417
- add tests
- interact directly with starknet address with DualVMToken
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1421)
> feat: dualVMToken starknet functions

- blockchain-tests-skip.yml
- kakarot_scripts/ef_tests/fetch.py
- src/kakarot/constants.cairo
- src/kakarot/instructions/block_information.cairo
- tests/end_to_end/bytecodes.py
- tests/src/kakarot/instructions/test_block_information.py
- tests/utils/constants.py
`BLOBBASEFEE` should return the `MIN_BASE_FEE_PER_BLOB_GAS` defined in  https://eips.ethereum.org/EIPS/eip-4844#gas-accounting instead of Zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1442)
> feat: blobbasefee return ONE

- blockchain-tests-skip.yml
- src/kakarot/errors.cairo
- src/kakarot/interpreter.cairo
ensure the sender nonce is not MAX_U64 otherwise reject tx.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1444)
> feat: ensure sender nonce doesnt overflow u64

- docs/general/accounts.md
- docs/general/kakarot_components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1446)
> docs: update docs

- .github/workflows/ci.yml
- src/kakarot/kakarot.cairo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1450)
> Skip CI jobs when no file change

- tests/utils/helpers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1454)
> Fix rlp_encode_signed_data util

- README.md
- src/backend/starknet.cairo
- src/kakarot/library.cairo
Hello
I fixed several spelling issues in order to ensure a better understanding,
Br, Elias.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1465)
> docs fix spelling issues

- kakarot_scripts/constants.py
- kakarot_scripts/utils/kakarot.py
- tests/utils/errors.py
Fixes issues with the end 2 end testing of Kakarot on Sepolia Starknet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1468)
> fix: end2end testing on sepolia

- cairo/kakarot-ssj/crates/contracts/src/kakarot_core/eth_rpc.cairo
- cairo/kakarot-ssj/crates/utils/src/constants.cairo
- cairo_zero/kakarot/constants.cairo
- cairo_zero/kakarot/library.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.py
- kakarot_scripts/constants.py
- tests/utils/constants.py
Use MAX_SAFE_CHAIN_ID for cairo / cairo-zero
See https://gist.github.com/rekmarks/a47bd5f2525936c4b8eee31a16345553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1472)
> fix: use MAX_SAFE_CHAIN_ID

- .github/workflows/ssj-ci.yml
SSJ resources should pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1474)
> ci: fix ssj resources

- kakarot_scripts/utils/kakarot.py
avoid overriding dict references
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1475)
> test: avoid overriding dict references

- .github/workflows/cairo-zero-ci.yml
- deployments/starknet-sepolia/deployments.json
- kakarot_scripts/benchmark_cairo_calls.py
- kakarot_scripts/compile_kakarot.py
- kakarot_scripts/constants.py
- kakarot_scripts/deploy_kakarot.py
- kakarot_scripts/utils/kakarot.py
- kakarot_scripts/utils/starknet.py
- kakarot_scripts/withdraw_accounts.py
- tests/end_to_end/CairoPrecompiles/Pragma/test_pragma_precompile.py
- tests/end_to_end/CairoPrecompiles/test_dual_vm_token.py
- tests/end_to_end/EvmPrecompiles/test_evm_precompiles.py
Not possible to use an Argent multisig account as account in the scripts.
Resolves #1411
- `get_starknet_account` can handle an Argent multisig account as sender.
- all invoke tx now use the same `execute_v1` function extracted from `starknet-py`.
- this function can be lazy and batch execute calls afterwards instead of executing them when called.
- also added cache of the class_hashes at compile step to speed up the deployment script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1476)
> Enable multisig for account

- README.md
The README currently suggests an outdated installation command for the uv tool. This command does not work
The installation command for uv has been updated in the README to reflect the latest recommended command. The new command uses the URL `https://astral.sh/uv/install.sh`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1479)
> docs: :memo: update uv installation command

- kakarot_scripts/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1481)
> Enforce kakarot chain id log to use 7 bytes'

- Makefile
reduced compute limits for tests to match prod
- reduce step limit for `__validate__` and `__execute__` endpoints for tests to match SN Sepolia (resp. 1m and 9m cairo steps)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1504)
> dev: reduce step limit per tx to be same as Sepolia SN

- .github/workflows/cairo-zero-ci.yml
- deployments/starknet-mainnet/deployments.json
- deployments/starknet-mainnet/kakarot_deployments.json
- deployments/starknet-mainnet/l1_addresses.json
- kakarot_scripts/constants.py
- kakarot_scripts/deployment/evm_deployments.py
- kakarot_scripts/deployment/kakarot_deployment.py
- kakarot_scripts/deployment/main.py
- kakarot_scripts/deployment/messaging_deployments.py
- kakarot_scripts/deployment/pre_eip155_deployments.py
- kakarot_scripts/deployment/starknet_deployments.py
- kakarot_scripts/utils/kakarot.py
- kakarot_scripts/utils/starknet.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1501)
> Raise if argent status is not TX_ACCEPTED_L2

- Makefile
bump katana to alpha16, whose genesis ETH token has camelCase AND snake_case entrypoints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1508)
> chore: bump katana

- solidity_contracts/src/CairoPrecompiles/CallCairoPrecompileTest.sol
- solidity_contracts/src/CairoPrecompiles/DualVmToken.sol
- solidity_contracts/src/CairoPrecompiles/MulticallCairoPrecompileTest.sol
- solidity_contracts/src/CairoPrecompiles/PragmaCaller.sol
- solidity_contracts/src/CairoPrecompiles/WhitelistedCallCairoLib.sol
- solidity_contracts/src/CairoPrecompiles/WhitelistedCallCairoPrecompileTest.sol
- tests/end_to_end/CairoPrecompiles/Pragma/test_pragma_precompile.py
Refactors the CairoLib and its usage.
The CairoLib from `kakarot-lib` now only exposes public, non-whitelisted entrypoints (including multicall).
As such, the DualVmToken and other contracts relying on the whitelisted `delegatecall` feature are using an internal `WhitelistedCallCairoLib` library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1510)
> refactor: CairoLib

- .github/workflows/cairo-zero-ci.yml
- Makefile
- README.md
- docs/CONTRIBUTING.md
- kakarot_scripts/setup/setup.py
- pyproject.toml
Closes #1500
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1502)
> dev: setup script

- .github/workflows/cairo-zero-release.yml
- .github/workflows/ssj-ci.yml
- Makefile
Fixes release job by:
- Copying the .env file to have an EVM_PRIVATE_KEY in environment (required for build)
- Adding a new `setup-ci` target that only sets up the bare minimum for the CIs to run.
Proof that it works: https://github.com/enitrat/kakarot/actions/runs/11566994717
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1552)
> ci: fix release job

- cairo/kakarot-ssj/crates/contracts/tests/test_kakarot_core.cairo
- cairo/kakarot-ssj/crates/evm/src/interpreter.cairo
- cairo_zero/kakarot/interpreter.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.py
- kakarot_scripts/utils/kakarot.py
- tests/end_to_end/CairoPrecompiles/test_whitelisted_call_cairo_precompile.py
Fixes an issue with the returndata of create txs, which was pushing `[<sn_addr>, <evm_addr>]` instead of `[<contract_code>]` in the returndata.
side note: the SSJ test would not run because it's ignored. There is some work regarding testing of SSJ which is out of scope for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1557)
> fix: returndata of create txs

- cairo_zero/tests/src/utils/test_bytes.py
- cairo_zero/utils/bytes.cairo
- tests/utils/errors.py
Resolves #1563
The loop will stop at 31 bytes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1573)
> [KGA-31] fix: felt_to_bytes_little loop stop condition

- cairo_zero/backend/starknet.cairo
Fixes the codehash assigned to an account upon deployment as per https://github.com/code-423n4/2024-09-kakarot-findings/issues/10
- In any case, the codehash of an account is keccak(code_bytes)
- IF that account has no code, nonce nor balance, then `extcodehash` opcode returns 0.
As such, upon deploying the starknet contract corresponding to an account, we should _always_ set the codehash to `self.code_hash`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1566)
> [KGA-82] [KGA-80] fix: codehash commitment

- cairo_zero/kakarot/precompiles/ripemd160.cairo
- cairo_zero/tests/src/kakarot/precompiles/test_ripemd160.py
Fix off by one error ripemd-160
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1575)
> [KGA-18] fix: off by one error ripemd-160

- README.md
- cairo_zero/kakarot/constants.cairo
- cairo_zero/kakarot/kakarot.cairo
- cairo_zero/kakarot/library.cairo
- cairo_zero/kakarot/storages.cairo
- cairo_zero/tests/src/kakarot/instructions/test_block_information.py
- cairo_zero/tests/src/kakarot/test_kakarot.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.py
- kakarot_scripts/constants.py
- kakarot_scripts/deployment/kakarot_deployment.py
- kakarot_scripts/deployment/starknet_deployments.py
- tests/utils/constants.py
Resolves #1530
Chain id is set in constructor and stored in storage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1571)
> feat: chain_id storage var

- cairo/kakarot-ssj/crates/utils/src/math.cairo
Fixes `pow` in SSJ
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1579)
> [KGA-3] [KGA-122] fix: SSJ pow

- cairo_zero/kakarot/precompiles/ripemd160.cairo
- cairo_zero/tests/src/kakarot/precompiles/test_ripemd160.py
- tests/utils/hints.py
Resolves #1561
Finalize the dict and reassign start after reseting the dict.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1577)
> [KGA-14] [KGA-28] [KGA-74] [KGA-132] [KGA-92] fix: finalize dictionary in RIPEMD160

- cairo_zero/tests/src/utils/test_eth_transaction.py
- cairo_zero/utils/eth_transaction.cairo
Assert the chain id does not overflow for legacy post eip 155 tx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1581)
> [KGA-65] fix: decode legacy chain id overflow

- cairo_zero/kakarot/accounts/account_contract.cairo
- cairo_zero/kakarot/library.cairo
- cairo_zero/tests/src/kakarot/accounts/test_account_contract.py
- solidity_contracts/src/CairoPrecompiles/KakarotReentrancyTest.sol
- tests/end_to_end/CairoPrecompiles/test_call_cairo_precompile.py
Reentrancy check is moved at Kakarot level in eth_call
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1582)
> [KGA-4] [KGA-118] [KGA-119] [KGA-127] [KGA-133] fix: reentrancy check in eth_call

- cairo_zero/kakarot/instructions/system_operations.cairo
- cairo_zero/kakarot/interpreter.cairo
- tests/end_to_end/test_kakarot.py
Set code_address of the deployment code to the created address. 
[ src/ethereum/cancun/utils/message.py](https://github.com/ethereum/execution-specs/blob/07f5747a43d62ef7f203d41d77005cb15ca5e434/src/ethereum/cancun/utils/message.py#L89-L90)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1587)
> [KGA-25] [KGA-73] fix: set code_address of the deployment code to the created address

- cairo_zero/kakarot/instructions/block_information.cairo
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
Last 10 blocks returns 0 for blockhash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1593)
> [KGA-32] [KGA-143] [KGA-86] [KGA-88]fix: last 10 blockhash are 0

- kakarot_scripts/setup/setup.py
**Fixed bug in `kakarot_scripts/check_resources.py` with wrong and not needed parameter.**
**0.1 day (2-3 hours)**
Resolves #1597
- `make check-resources` now works without any bugs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1599)
> dev: fix ssj ci resources

- blockchain-tests-skip.yml
- cairo_zero/tests/src/utils/test_dict.cairo
- cairo_zero/utils/dict.cairo
Use `default_dict_finalize` with 0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1592)
> [KGA-39] fix: default_dict_copy finalize with default value 0

- cairo_zero/utils/uint256.cairo
removes a useless line that compute `uint256_fast_exp` one too many times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1603)
> [KGA-89] dev: remove useless computation in uint256_fast_exp"

- cairo_zero/kakarot/gas.cairo
- cairo_zero/tests/src/kakarot/test_gas.cairo
- cairo_zero/tests/src/kakarot/test_gas.py
- cairo_zero/tests/src/utils/test_bytes.py
- tests/utils/constants.py
Fixes computation on high memory offsets.
The remediation proposed by the audit finding was not sufficient enough. This one looks fine, although a bit more costly (even though uint256_add is not that computationally intensive)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1604)
> [KGA-87] fix: high offset memory expansion computations

- .github/workflows/cairo-zero-nightly-fuzzing.yml
- Makefile
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1609)
> Add setup-ci and workflow dispatch

- .github/workflows/cairo-zero-ci.yml
- cairo_zero/backend/starknet.cairo
- cairo_zero/kakarot/library.cairo
- cairo_zero/kakarot/storages.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.py
- tests/utils/syscall_handler.py
Updates the base fee mechanism.
In the EVM there can only be one base fee for a given block.
Thus, we use an index to manage two different base fees:
- The base fee to use for the current block (index: 'current_block')
- The base fee to use for the next block (index: 'next_block')
The startegy is:
- when getting the base fee, check if you can get the one from the 'next_block' (if block_number > next_fee_start_block_number)
- if yes, then update the value in `current_block` and return the new value
- otherwise, return the value from `current_block`     
When setting the base_fee, it will be applicable starting from `block_number + 1`.
Note: for tests we have to manually patch both `addr` and `addr+1` as we'restoring two values.
- - -
This change is [<img …
> [KGA-34] feat: update base fee starting from next block only

- cairo_zero/kakarot/instructions/system_operations.cairo
Removes a portion of dead code that cheks the return value of the `add_transfer` function in `exec_create`. Because the case where the sender doesn't have enough balance is manually handled before, this branch can not be executed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1611)
> [KGA-64] dev: remove dead code in exec_create

- cairo_zero/kakarot/accounts/library.cairo
The event is emitted with at most 297 felts of response_len, but the function returns the full data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot/1612)
> [KGA-72] fix: return uncapped return_data_len from execute_from_outside

- README.md
- fix mermaid diagram in main readme 
error was previously:
```
Unable to render rich display
Parse error on line 26:
...tecode() A ->> K: K ->> I: Inte
----------------------^
Expecting 'NEWLINE', 'AS', ',', 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'BIDIRECTIONAL_SOLID_ARROW', 'DOTTED_ARROW', 'BIDIRECTIONAL_DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', 'SOLID_POINT', 'DOTTED_POINT', 'TXT', got 'INVALID'
For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix: fix mermaid diagram in readme

- .github/workflows/cairo-zero-ci.yml
- .github/workflows/cairo-zero-nightly-fuzzing.yml
- kakarot_scripts/setup/setup.py
Latest foundry nightly is bugged with WETH9. Fix the version to the latest working one.
> fix: fixed foundry version to a working one

- cairo_zero/tests/src/utils/test_eth_transaction.py
- cairo_zero/utils/eth_transaction.cairo
- tests/utils/constants.py
Fixes an [issue](https://github.com/code-423n4/2024-09-kakarot-findings/issues/81) where parsing malformed access lists could have undefined behavior due to OOB reads. This had no impact on the protocol whatsoever and could only discard the benefits from eip2930
> [KGA-49]: fix OOB read in parse_storage_keys on malformed inputs

- cairo_zero/kakarot/gas.cairo
- cairo_zero/tests/src/kakarot/test_gas.py
Fixes the early return condition in `calculate_gas_extend_memory` that was off-by-one.
This had no impact on the code, as the correct memory was computed after. This just did not early returned in all cases.
> [KGA-100] [KGA-56] fix: memory expansion early return condition

- cairo_zero/kakarot/instructions/system_operations.cairo
https://github.com/code-423n4/2024-09-kakarot-findings/issues/83
Selftdestruct send to the burn address
> [KGA-46]fix: Selfdestruct send to burn address

- cairo_zero/tests/src/utils/test_utils.py
- cairo_zero/utils/utils.cairo
- tests/utils/hints.py
Fixes an underconstrained hint in initialize_jumpdests. Avoids a malicious prover to continue iterating over the bytecode limit and consuming extra resources, but has no impact over code execution
https://github.com/code-423n4/2024-09-kakarot-findings/issues/26
> [KGA-51] fix: underconstrained hint in initialize_jumpdests

- cairo_zero/kakarot/accounts/account_contract.cairo
- cairo_zero/kakarot/accounts/library.cairo
- cairo_zero/kakarot/constants.cairo
- cairo_zero/kakarot/interfaces/interfaces.cairo
- cairo_zero/kakarot/kakarot.cairo
- cairo_zero/kakarot/library.cairo
- cairo_zero/tests/src/kakarot/accounts/test_account_contract.cairo
- cairo_zero/tests/src/kakarot/accounts/test_account_contract.py
- cairo_zero/tests/src/kakarot/test_kakarot.cairo
- cairo_zero/tests/src/kakarot/test_kakarot.py
- cairo_zero/utils/signature.cairo
https://github.com/code-423n4/2024-09-kakarot-findings/issues/66
*  Missing boundary check in EVM transaction decoding
adds a check to ensure [call_array].data_offset + [call_array].data_len <= calldata_len
* Several of the stack_size_diff values defined in constants.cairo are off
put the right values
* After Kakarot's native token is changed, an approval from account_contract instances can't be re-triggered
remove the setter, this will not change
* Some invalid values for the v field in Ethereum signatures are accepted
add a check to ensure y_parity is 0 or 1
> [KGA-98] QA report 66

- cairo_zero/backend/starknet.cairo
- cairo_zero/kakarot/account.cairo
- cairo_zero/kakarot/instructions/environmental_information.cairo
- cairo_zero/tests/src/kakarot/test_account.cairo
Code hash for eoa cannot be stored as they can change. Put the logic of 0 or empty code hash in function.
> fix: do not store code hash for EOAs

- README.md
This PR fixes broken links in the `README.md` file to ensure all references point to the correct resources.
0.2 days
Currently, some links in the `README.md` are outdated or broken, causing navigation issues for readers.
Resolves: No linked issue
- Updated the precompiles link to point to the correct `cairo-precompiles` page.
- Fixed the test RLP library link to use the correct relative path.
- Updated the deploy script link to point to the correct file location.
> fix: broken links README.md

- cairo_zero/kakarot/errors.cairo
- cairo_zero/kakarot/precompiles/kakarot_precompiles.cairo
- cairo_zero/tests/src/kakarot/precompiles/test_blake2f.py
- tests/end_to_end/CairoPrecompiles/test_multicall_cairo_precompile.py
- tests/end_to_end/PlainOpcodes/test_plain_opcodes.py
precompile
Check the number of expected calls is equal to the number of actual calls made
> fix: check numbers of calls multicall precompile

- aws_lambda/fee_balancer/cdk.json
This PR fixes a typo in the AWS CDK configuration where "patterns" was incorrectly spelled as "patters".
File: `aws_lambda/fee_balancer/cdk.json`
"@aws-cdk/aws-route53-patters:useCertificate": true,
"@aws-cdk/aws-route53-patterns:useCertificate": true,
This fix ensures proper configuration of the AWS Route53 patterns module. The incorrect spelling could lead to the certificate configuration being ignored, potentially affecting SSL/TLS certificate management in Route53.
> Shows the incorrect spelling "patters" in the configuration
> Shows the corrected spelling "patterns" in the configuration
> Correct AWS Route53 patterns module name in CDK configuration

- cairo_zero/backend/starknet.cairo
- cairo_zero/kakarot/account.cairo
- cairo_zero/kakarot/accounts/account_contract.cairo
- cairo_zero/kakarot/accounts/library.cairo
- cairo_zero/kakarot/instructions/environmental_information.cairo
- cairo_zero/kakarot/interfaces/interfaces.cairo
- cairo_zero/tests/src/kakarot/accounts/test_account_contract.cairo
- cairo_zero/tests/src/kakarot/accounts/test_account_contract.py
- cairo_zero/tests/src/kakarot/test_account.cairo
Overwrite fix to codehash done in #1644
Motivation:
I prefer a solution that avoids having invalid states altogether.
- All accounts have a code_hash set to keccak256("") when deployed
- Any modification to the account's code will also modify it's code_hash 
- extcodehash simply check the account_exists = has_code_or_nonce or has_balance condition to know whether to return 0 or code_hash
which is more inline with the spec. The `codehash` of an account is _never_ zero, the `extcodehash` is.
> overwrite fix to codehash

- cairo_zero/kakarot/precompiles/kakarot_precompiles.cairo
- tests/end_to_end/CairoPrecompiles/test_multicall_cairo_precompile.py
The fix made previously in #1647 did not take into account that the starknet state might have been changed.
If we ever encounter a case where the multicall payload was wrongly formed and the number of executed calls doesn't match the input, we should revert the tx immediately.
> fix: revert tx if multicall input is incoherent

- .github/workflows/ssj-ef-tests.yml
- cairo/kakarot-ssj/blockchain-tests-skip.yml
- cairo/kakarot-ssj/crates/contracts/Scarb.toml
- Ensured that we could run the CI in native mode by having the right llvm deps installed
HOWEVER
- Disabled Cairo Native as the run was taking an overly long time.
- updated SSJ skipfile because some tests are now Out Of Resources.
> ci: disable cairo-native
